// Sensor protocol v3: the sensor <-> platform transport
// (docs/rfcs/RFC-059-sensor-transport-v3.md).
//
// One service, two bindings served by the same handlers:
//   - gRPC over HTTP/2 on the dedicated sensor host, authenticated by a client
//     certificate from the sensor CA (mTLS, TLS 1.3);
//   - Connect over HTTPS (HTTP/1.1 or HTTP/2) under /api/v3/sensor on the
//     platform host, authenticated by an RFC 9421 request signature with the
//     sensor's key, as protocol v2.
//
// v3 carries the resource model of protocol v2 (RFC-026 results, RFC-029
// control plane). The envelope is typed: identifiers, sequence numbers, lease
// epochs, encodings, digests, entity tags and transport facts. A document whose
// schema is owned by another specification travels as its JSON bytes, unchanged:
// the heartbeat body and answer (RFC-029), commands (RFC-029), CTIS reports
// (RFC-026), the manifest (RFC-033), the config report and suppressions.
//
// Rules every message follows:
//   - No message names a tenant. The tenant and the sensor are those of the
//     authenticated identity (certificate or signature), never of a field.
//   - A command or report id of another sensor or tenant is NOT_FOUND.
//   - An error carries an openctem.sensor.v3.Problem detail: the RFC 9457
//     problem document v2 would have answered, with its HTTP status.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: openctem/sensor/v3/sensor.proto

package sensorv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Binding is how a sensor reaches the platform.
type Binding int32

const (
	Binding_BINDING_UNSPECIFIED Binding = 0
	// gRPC over HTTP/2 with a client certificate (mTLS).
	Binding_BINDING_GRPC Binding = 1
	// Connect over HTTPS with RFC 9421 request signatures.
	Binding_BINDING_HTTPS Binding = 2
	// Protocol v2 (JSON resources over HTTPS).
	Binding_BINDING_V2 Binding = 3
)

// Enum value maps for Binding.
var (
	Binding_name = map[int32]string{
		0: "BINDING_UNSPECIFIED",
		1: "BINDING_GRPC",
		2: "BINDING_HTTPS",
		3: "BINDING_V2",
	}
	Binding_value = map[string]int32{
		"BINDING_UNSPECIFIED": 0,
		"BINDING_GRPC":        1,
		"BINDING_HTTPS":       2,
		"BINDING_V2":          3,
	}
)

func (x Binding) Enum() *Binding {
	p := new(Binding)
	*p = x
	return p
}

func (x Binding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Binding) Descriptor() protoreflect.EnumDescriptor {
	return file_openctem_sensor_v3_sensor_proto_enumTypes[0].Descriptor()
}

func (Binding) Type() protoreflect.EnumType {
	return &file_openctem_sensor_v3_sensor_proto_enumTypes[0]
}

func (x Binding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Binding.Descriptor instead.
func (Binding) EnumDescriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{0}
}

// CommandTransition is the state change a sensor asks for.
type CommandTransition int32

const (
	CommandTransition_COMMAND_TRANSITION_UNSPECIFIED CommandTransition = 0
	CommandTransition_COMMAND_TRANSITION_CLAIM       CommandTransition = 1
	CommandTransition_COMMAND_TRANSITION_START       CommandTransition = 2
	CommandTransition_COMMAND_TRANSITION_COMPLETE    CommandTransition = 3
	CommandTransition_COMMAND_TRANSITION_FAIL        CommandTransition = 4
	CommandTransition_COMMAND_TRANSITION_RELEASE     CommandTransition = 5
)

// Enum value maps for CommandTransition.
var (
	CommandTransition_name = map[int32]string{
		0: "COMMAND_TRANSITION_UNSPECIFIED",
		1: "COMMAND_TRANSITION_CLAIM",
		2: "COMMAND_TRANSITION_START",
		3: "COMMAND_TRANSITION_COMPLETE",
		4: "COMMAND_TRANSITION_FAIL",
		5: "COMMAND_TRANSITION_RELEASE",
	}
	CommandTransition_value = map[string]int32{
		"COMMAND_TRANSITION_UNSPECIFIED": 0,
		"COMMAND_TRANSITION_CLAIM":       1,
		"COMMAND_TRANSITION_START":       2,
		"COMMAND_TRANSITION_COMPLETE":    3,
		"COMMAND_TRANSITION_FAIL":        4,
		"COMMAND_TRANSITION_RELEASE":     5,
	}
)

func (x CommandTransition) Enum() *CommandTransition {
	p := new(CommandTransition)
	*p = x
	return p
}

func (x CommandTransition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandTransition) Descriptor() protoreflect.EnumDescriptor {
	return file_openctem_sensor_v3_sensor_proto_enumTypes[1].Descriptor()
}

func (CommandTransition) Type() protoreflect.EnumType {
	return &file_openctem_sensor_v3_sensor_proto_enumTypes[1]
}

func (x CommandTransition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandTransition.Descriptor instead.
func (CommandTransition) EnumDescriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{1}
}

// Problem is the error detail of every refused call: the RFC 9457 problem
// document protocol v2 answers, and its HTTP status.
type Problem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status v2 would have answered (400, 401, 403, 404, 409, 413, 415,
	// 422, 429, 500, 503).
	HttpStatus int32 `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	// Problem type URI (https://openctem.io/problems/sensor/...).
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// The problem document, application/problem+json.
	ProblemJson []byte `protobuf:"bytes,3,opt,name=problem_json,json=problemJson,proto3" json:"problem_json,omitempty"`
	// Seconds to wait before retrying, when the platform advises it.
	RetryAfterSeconds int32 `protobuf:"varint,4,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *Problem) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *Problem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Problem) GetProblemJson() []byte {
	if x != nil {
		return x.ProblemJson
	}
	return nil
}

func (x *Problem) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

// Transport describes the sensor's connection, reported on every heartbeat.
// The platform records the binding it actually served the call on; the sensor
// only explains why it is not on the preferred one.
type Transport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The binding the sensor believes it uses (informational).
	Binding Binding `protobuf:"varint,1,opt,name=binding,proto3,enum=openctem.sensor.v3.Binding" json:"binding,omitempty"`
	// Why the sensor is not on gRPC: "" when it is. A short machine-readable
	// reason (e.g. "http2_refused", "handshake_failed", "forced_by_config"),
	// at most 64 characters, then free text up to 256 characters in total.
	FallbackReason string `protobuf:"bytes,2,opt,name=fallback_reason,json=fallbackReason,proto3" json:"fallback_reason,omitempty"`
	// When the sensor started using this binding.
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *Transport) GetBinding() Binding {
	if x != nil {
		return x.Binding
	}
	return Binding_BINDING_UNSPECIFIED
}

func (x *Transport) GetFallbackReason() string {
	if x != nil {
		return x.FallbackReason
	}
	return ""
}

func (x *Transport) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{2}
}

type HelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol level of this answer: 3.
	Protocol int32 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// The protocol v2 hello document (features, media types, encodings,
	// digests, limits), application/json.
	HelloJson []byte `protobuf:"bytes,2,opt,name=hello_json,json=helloJson,proto3" json:"hello_json,omitempty"`
	// host:port of the gRPC (mTLS) binding; "" when this platform serves only
	// the HTTPS binding.
	GrpcEndpoint string `protobuf:"bytes,3,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	// The binding this answer was served on.
	Binding       Binding `protobuf:"varint,4,opt,name=binding,proto3,enum=openctem.sensor.v3.Binding" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{3}
}

func (x *HelloResponse) GetProtocol() int32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *HelloResponse) GetHelloJson() []byte {
	if x != nil {
		return x.HelloJson
	}
	return nil
}

func (x *HelloResponse) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *HelloResponse) GetBinding() Binding {
	if x != nil {
		return x.Binding
	}
	return Binding_BINDING_UNSPECIFIED
}

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The heartbeat body of protocol v2 (RFC-029 §4.3), application/json.
	HeartbeatJson []byte `protobuf:"bytes,1,opt,name=heartbeat_json,json=heartbeatJson,proto3" json:"heartbeat_json,omitempty"`
	// How the sensor is connected.
	Transport     *Transport `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetHeartbeatJson() []byte {
	if x != nil {
		return x.HeartbeatJson
	}
	return nil
}

func (x *HeartbeatRequest) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The heartbeat answer of protocol v2 (sensor and tenant ids, status,
	// doorbell hints, actions, cancel ids), application/json.
	HeartbeatJson []byte `protobuf:"bytes,1,opt,name=heartbeat_json,json=heartbeatJson,proto3" json:"heartbeat_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetHeartbeatJson() []byte {
	if x != nil {
		return x.HeartbeatJson
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{6}
}

// SubscribeResponse is one event of the control stream: the doorbell as it
// stands now. The sensor acts on it exactly as on a heartbeat answer.
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "ok" or "paused".
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Commands waiting for this sensor (capped by the platform).
	PendingJobs int32 `protobuf:"varint,2,opt,name=pending_jobs,json=pendingJobs,proto3" json:"pending_jobs,omitempty"`
	// Actions to take: claim, cancel, pause, drain, rotate_key,
	// send_manifest, send_config_report, ...
	Actions []string `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	// Commands this sensor holds that were cancelled.
	CancelCommandIds []string `protobuf:"bytes,4,rep,name=cancel_command_ids,json=cancelCommandIds,proto3" json:"cancel_command_ids,omitempty"`
	// Version of the sensor's configuration (re-read the manifest policy when
	// it changes).
	ConfigVersion string `protobuf:"bytes,5,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// A keepalive carries no new information.
	Keepalive     bool `protobuf:"varint,6,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubscribeResponse) GetPendingJobs() int32 {
	if x != nil {
		return x.PendingJobs
	}
	return 0
}

func (x *SubscribeResponse) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *SubscribeResponse) GetCancelCommandIds() []string {
	if x != nil {
		return x.CancelCommandIds
	}
	return nil
}

func (x *SubscribeResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *SubscribeResponse) GetKeepalive() bool {
	if x != nil {
		return x.Keepalive
	}
	return false
}

type ClaimCommandsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Most commands to claim (1..100).
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Optional sensor features, as X-OpenCTEM-Sensor-Features on v2.
	Features      []string `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCommandsRequest) Reset() {
	*x = ClaimCommandsRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCommandsRequest) ProtoMessage() {}

func (x *ClaimCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCommandsRequest.ProtoReflect.Descriptor instead.
func (*ClaimCommandsRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimCommandsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ClaimCommandsRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type ClaimCommandsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol v2 command list ({"commands": [...]}), application/json.
	CommandsJson  []byte `protobuf:"bytes,1,opt,name=commands_json,json=commandsJson,proto3" json:"commands_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCommandsResponse) Reset() {
	*x = ClaimCommandsResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCommandsResponse) ProtoMessage() {}

func (x *ClaimCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCommandsResponse.ProtoReflect.Descriptor instead.
func (*ClaimCommandsResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{9}
}

func (x *ClaimCommandsResponse) GetCommandsJson() []byte {
	if x != nil {
		return x.CommandsJson
	}
	return nil
}

type TransitionCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The command, a UUID.
	CommandId  string            `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Transition CommandTransition `protobuf:"varint,2,opt,name=transition,proto3,enum=openctem.sensor.v3.CommandTransition" json:"transition,omitempty"`
	// The lease epoch the sensor holds the command under; a command claimed
	// again since refuses the change.
	LeaseEpoch *int64 `protobuf:"varint,3,opt,name=lease_epoch,json=leaseEpoch,proto3,oneof" json:"lease_epoch,omitempty"`
	// The v2 request body of the transition (complete: result; fail: error
	// and refusal; release: reason), application/json. Empty for none.
	BodyJson      []byte `protobuf:"bytes,4,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionCommandRequest) Reset() {
	*x = TransitionCommandRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionCommandRequest) ProtoMessage() {}

func (x *TransitionCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionCommandRequest.ProtoReflect.Descriptor instead.
func (*TransitionCommandRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{10}
}

func (x *TransitionCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *TransitionCommandRequest) GetTransition() CommandTransition {
	if x != nil {
		return x.Transition
	}
	return CommandTransition_COMMAND_TRANSITION_UNSPECIFIED
}

func (x *TransitionCommandRequest) GetLeaseEpoch() int64 {
	if x != nil && x.LeaseEpoch != nil {
		return *x.LeaseEpoch
	}
	return 0
}

func (x *TransitionCommandRequest) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

type TransitionCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The command after the transition, protocol v2 shape, application/json.
	CommandJson   []byte `protobuf:"bytes,1,opt,name=command_json,json=commandJson,proto3" json:"command_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionCommandResponse) Reset() {
	*x = TransitionCommandResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionCommandResponse) ProtoMessage() {}

func (x *TransitionCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionCommandResponse.ProtoReflect.Descriptor instead.
func (*TransitionCommandResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{11}
}

func (x *TransitionCommandResponse) GetCommandJson() []byte {
	if x != nil {
		return x.CommandJson
	}
	return nil
}

type AppendCommandLogsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// The protocol v2 logs body, application/json.
	BodyJson      []byte `protobuf:"bytes,2,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendCommandLogsRequest) Reset() {
	*x = AppendCommandLogsRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendCommandLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendCommandLogsRequest) ProtoMessage() {}

func (x *AppendCommandLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendCommandLogsRequest.ProtoReflect.Descriptor instead.
func (*AppendCommandLogsRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{12}
}

func (x *AppendCommandLogsRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AppendCommandLogsRequest) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

type AppendCommandLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol v2 answer, application/json.
	ResponseJson  []byte `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendCommandLogsResponse) Reset() {
	*x = AppendCommandLogsResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendCommandLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendCommandLogsResponse) ProtoMessage() {}

func (x *AppendCommandLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendCommandLogsResponse.ProtoReflect.Descriptor instead.
func (*AppendCommandLogsResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{13}
}

func (x *AppendCommandLogsResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type PutResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Idempotency key of the report, a UUID chosen by the sensor.
	ReportId string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// The command the report belongs to, a UUID; "" for a report of no command.
	CommandId string `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// The segment number (0-based); absent for a whole report in one call.
	Segment *uint32 `protobuf:"varint,3,opt,name=segment,proto3,oneof" json:"segment,omitempty"`
	// The content as sent: CTIS JSON, possibly compressed.
	Content []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// application/vnd.openctem.ctis.v1+json
	ContentType string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// "", "gzip" or "zstd".
	ContentEncoding string `protobuf:"bytes,6,opt,name=content_encoding,json=contentEncoding,proto3" json:"content_encoding,omitempty"`
	// RFC 9530 Content-Digest of content as sent (sha-256 or sha-512).
	ContentDigest string `protobuf:"bytes,7,opt,name=content_digest,json=contentDigest,proto3" json:"content_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResultRequest) Reset() {
	*x = PutResultRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResultRequest) ProtoMessage() {}

func (x *PutResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResultRequest.ProtoReflect.Descriptor instead.
func (*PutResultRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{14}
}

func (x *PutResultRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *PutResultRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PutResultRequest) GetSegment() uint32 {
	if x != nil && x.Segment != nil {
		return *x.Segment
	}
	return 0
}

func (x *PutResultRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PutResultRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PutResultRequest) GetContentEncoding() string {
	if x != nil {
		return x.ContentEncoding
	}
	return ""
}

func (x *PutResultRequest) GetContentDigest() string {
	if x != nil {
		return x.ContentDigest
	}
	return ""
}

type PutResultResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when this call created the report or segment (v2: 202).
	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	// The report status resource, application/json.
	StatusJson []byte `protobuf:"bytes,2,opt,name=status_json,json=statusJson,proto3" json:"status_json,omitempty"`
	// Seconds before polling the status again; 0 when the state is final.
	RetryAfterSeconds int32 `protobuf:"varint,3,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PutResultResponse) Reset() {
	*x = PutResultResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResultResponse) ProtoMessage() {}

func (x *PutResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResultResponse.ProtoReflect.Descriptor instead.
func (*PutResultResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{15}
}

func (x *PutResultResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *PutResultResponse) GetStatusJson() []byte {
	if x != nil {
		return x.StatusJson
	}
	return nil
}

func (x *PutResultResponse) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

type CommitResultRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ReportId  string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	CommandId string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// The protocol v2 commit body, application/json.
	BodyJson      []byte `protobuf:"bytes,3,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResultRequest) Reset() {
	*x = CommitResultRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResultRequest) ProtoMessage() {}

func (x *CommitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResultRequest.ProtoReflect.Descriptor instead.
func (*CommitResultRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{16}
}

func (x *CommitResultRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *CommitResultRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommitResultRequest) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

type CommitResultResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Created           bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	StatusJson        []byte                 `protobuf:"bytes,2,opt,name=status_json,json=statusJson,proto3" json:"status_json,omitempty"`
	RetryAfterSeconds int32                  `protobuf:"varint,3,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommitResultResponse) Reset() {
	*x = CommitResultResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResultResponse) ProtoMessage() {}

func (x *CommitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResultResponse.ProtoReflect.Descriptor instead.
func (*CommitResultResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{17}
}

func (x *CommitResultResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *CommitResultResponse) GetStatusJson() []byte {
	if x != nil {
		return x.StatusJson
	}
	return nil
}

func (x *CommitResultResponse) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

type GetResultStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultStatusRequest) Reset() {
	*x = GetResultStatusRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultStatusRequest) ProtoMessage() {}

func (x *GetResultStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultStatusRequest.ProtoReflect.Descriptor instead.
func (*GetResultStatusRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{18}
}

func (x *GetResultStatusRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type GetResultStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StatusJson        []byte                 `protobuf:"bytes,1,opt,name=status_json,json=statusJson,proto3" json:"status_json,omitempty"`
	RetryAfterSeconds int32                  `protobuf:"varint,2,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetResultStatusResponse) Reset() {
	*x = GetResultStatusResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultStatusResponse) ProtoMessage() {}

func (x *GetResultStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultStatusResponse.ProtoReflect.Descriptor instead.
func (*GetResultStatusResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{19}
}

func (x *GetResultStatusResponse) GetStatusJson() []byte {
	if x != nil {
		return x.StatusJson
	}
	return nil
}

func (x *GetResultStatusResponse) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

type AbandonResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonResultRequest) Reset() {
	*x = AbandonResultRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonResultRequest) ProtoMessage() {}

func (x *AbandonResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonResultRequest.ProtoReflect.Descriptor instead.
func (*AbandonResultRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{20}
}

func (x *AbandonResultRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type AbandonResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonResultResponse) Reset() {
	*x = AbandonResultResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonResultResponse) ProtoMessage() {}

func (x *AbandonResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonResultResponse.ProtoReflect.Descriptor instead.
func (*AbandonResultResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{21}
}

type PutManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The manifest (RFC-033, schema 1), application/json.
	ManifestJson  []byte `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutManifestRequest) Reset() {
	*x = PutManifestRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutManifestRequest) ProtoMessage() {}

func (x *PutManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutManifestRequest.ProtoReflect.Descriptor instead.
func (*PutManifestRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{22}
}

func (x *PutManifestRequest) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

type PutManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseJson  []byte                 `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutManifestResponse) Reset() {
	*x = PutManifestResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutManifestResponse) ProtoMessage() {}

func (x *PutManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutManifestResponse.ProtoReflect.Descriptor instead.
func (*PutManifestResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{23}
}

func (x *PutManifestResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{24}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseJson  []byte                 `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{25}
}

func (x *GetManifestResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type PutConfigReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The config report (schema 1), application/json.
	ReportJson    []byte `protobuf:"bytes,1,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutConfigReportRequest) Reset() {
	*x = PutConfigReportRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutConfigReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutConfigReportRequest) ProtoMessage() {}

func (x *PutConfigReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutConfigReportRequest.ProtoReflect.Descriptor instead.
func (*PutConfigReportRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{26}
}

func (x *PutConfigReportRequest) GetReportJson() []byte {
	if x != nil {
		return x.ReportJson
	}
	return nil
}

type PutConfigReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseJson  []byte                 `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutConfigReportResponse) Reset() {
	*x = PutConfigReportResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutConfigReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutConfigReportResponse) ProtoMessage() {}

func (x *PutConfigReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutConfigReportResponse.ProtoReflect.Descriptor instead.
func (*PutConfigReportResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{27}
}

func (x *PutConfigReportResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type GetSuppressionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entity tag of the copy the sensor holds; "" for none.
	Etag          string `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuppressionsRequest) Reset() {
	*x = GetSuppressionsRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuppressionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuppressionsRequest) ProtoMessage() {}

func (x *GetSuppressionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuppressionsRequest.ProtoReflect.Descriptor instead.
func (*GetSuppressionsRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{28}
}

func (x *GetSuppressionsRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type GetSuppressionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the sensor's copy is current; suppressions_json is then empty.
	NotModified bool   `protobuf:"varint,1,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	Etag        string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	// The protocol v2 suppression list, application/json.
	SuppressionsJson []byte `protobuf:"bytes,3,opt,name=suppressions_json,json=suppressionsJson,proto3" json:"suppressions_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSuppressionsResponse) Reset() {
	*x = GetSuppressionsResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuppressionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuppressionsResponse) ProtoMessage() {}

func (x *GetSuppressionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuppressionsResponse.ProtoReflect.Descriptor instead.
func (*GetSuppressionsResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{29}
}

func (x *GetSuppressionsResponse) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

func (x *GetSuppressionsResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GetSuppressionsResponse) GetSuppressionsJson() []byte {
	if x != nil {
		return x.SuppressionsJson
	}
	return nil
}

type CheckFingerprintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFingerprintsRequest) Reset() {
	*x = CheckFingerprintsRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFingerprintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFingerprintsRequest) ProtoMessage() {}

func (x *CheckFingerprintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFingerprintsRequest.ProtoReflect.Descriptor instead.
func (*CheckFingerprintsRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{30}
}

func (x *CheckFingerprintsRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type CheckFingerprintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseJson  []byte                 `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFingerprintsResponse) Reset() {
	*x = CheckFingerprintsResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFingerprintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFingerprintsResponse) ProtoMessage() {}

func (x *CheckFingerprintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFingerprintsResponse.ProtoReflect.Descriptor instead.
func (*CheckFingerprintsResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{31}
}

func (x *CheckFingerprintsResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type BaselineDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaselineDiffRequest) Reset() {
	*x = BaselineDiffRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineDiffRequest) ProtoMessage() {}

func (x *BaselineDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineDiffRequest.ProtoReflect.Descriptor instead.
func (*BaselineDiffRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{32}
}

func (x *BaselineDiffRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type BaselineDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseJson  []byte                 `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaselineDiffResponse) Reset() {
	*x = BaselineDiffResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineDiffResponse) ProtoMessage() {}

func (x *BaselineDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineDiffResponse.ProtoReflect.Descriptor instead.
func (*BaselineDiffResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{33}
}

func (x *BaselineDiffResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type IssueCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCertificateRequest) Reset() {
	*x = IssueCertificateRequest{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCertificateRequest) ProtoMessage() {}

func (x *IssueCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCertificateRequest.ProtoReflect.Descriptor instead.
func (*IssueCertificateRequest) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{34}
}

type IssueCertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client certificate followed by any intermediates, PEM.
	CertificateChainPem string `protobuf:"bytes,1,opt,name=certificate_chain_pem,json=certificateChainPem,proto3" json:"certificate_chain_pem,omitempty"`
	// The CA certificates to pin for the gRPC binding (verify the platform's
	// server certificate against these only), PEM.
	CaBundlePem string                 `protobuf:"bytes,2,opt,name=ca_bundle_pem,json=caBundlePem,proto3" json:"ca_bundle_pem,omitempty"`
	NotBefore   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// When to ask for the next certificate (two thirds of the lifetime).
	RenewAfter *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=renew_after,json=renewAfter,proto3" json:"renew_after,omitempty"`
	// host:port of the gRPC binding.
	GrpcEndpoint  string `protobuf:"bytes,6,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCertificateResponse) Reset() {
	*x = IssueCertificateResponse{}
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCertificateResponse) ProtoMessage() {}

func (x *IssueCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openctem_sensor_v3_sensor_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCertificateResponse.ProtoReflect.Descriptor instead.
func (*IssueCertificateResponse) Descriptor() ([]byte, []int) {
	return file_openctem_sensor_v3_sensor_proto_rawDescGZIP(), []int{35}
}

func (x *IssueCertificateResponse) GetCertificateChainPem() string {
	if x != nil {
		return x.CertificateChainPem
	}
	return ""
}

func (x *IssueCertificateResponse) GetCaBundlePem() string {
	if x != nil {
		return x.CaBundlePem
	}
	return ""
}

func (x *IssueCertificateResponse) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *IssueCertificateResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *IssueCertificateResponse) GetRenewAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.RenewAfter
	}
	return nil
}

func (x *IssueCertificateResponse) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

var File_openctem_sensor_v3_sensor_proto protoreflect.FileDescriptor

const file_openctem_sensor_v3_sensor_proto_rawDesc = "" +
	"\n" +
	"\x1fopenctem/sensor/v3/sensor.proto\x12\x12openctem.sensor.v3\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n" +
	"\aProblem\x12\x1f\n" +
	"\vhttp_status\x18\x01 \x01(\x05R\n" +
	"httpStatus\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fproblem_json\x18\x03 \x01(\fR\vproblemJson\x12.\n" +
	"\x13retry_after_seconds\x18\x04 \x01(\x05R\x11retryAfterSeconds\"\x9d\x01\n" +
	"\tTransport\x125\n" +
	"\abinding\x18\x01 \x01(\x0e2\x1b.openctem.sensor.v3.BindingR\abinding\x12'\n" +
	"\x0ffallback_reason\x18\x02 \x01(\tR\x0efallbackReason\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"\x0e\n" +
	"\fHelloRequest\"\xa6\x01\n" +
	"\rHelloResponse\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\x05R\bprotocol\x12\x1d\n" +
	"\n" +
	"hello_json\x18\x02 \x01(\fR\thelloJson\x12#\n" +
	"\rgrpc_endpoint\x18\x03 \x01(\tR\fgrpcEndpoint\x125\n" +
	"\abinding\x18\x04 \x01(\x0e2\x1b.openctem.sensor.v3.BindingR\abinding\"v\n" +
	"\x10HeartbeatRequest\x12%\n" +
	"\x0eheartbeat_json\x18\x01 \x01(\fR\rheartbeatJson\x12;\n" +
	"\ttransport\x18\x02 \x01(\v2\x1d.openctem.sensor.v3.TransportR\ttransport\":\n" +
	"\x11HeartbeatResponse\x12%\n" +
	"\x0eheartbeat_json\x18\x01 \x01(\fR\rheartbeatJson\"\x12\n" +
	"\x10SubscribeRequest\"\xdb\x01\n" +
	"\x11SubscribeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fpending_jobs\x18\x02 \x01(\x05R\vpendingJobs\x12\x18\n" +
	"\aactions\x18\x03 \x03(\tR\aactions\x12,\n" +
	"\x12cancel_command_ids\x18\x04 \x03(\tR\x10cancelCommandIds\x12%\n" +
	"\x0econfig_version\x18\x05 \x01(\tR\rconfigVersion\x12\x1c\n" +
	"\tkeepalive\x18\x06 \x01(\bR\tkeepalive\"H\n" +
	"\x14ClaimCommandsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeatures\"<\n" +
	"\x15ClaimCommandsResponse\x12#\n" +
	"\rcommands_json\x18\x01 \x01(\fR\fcommandsJson\"\xd3\x01\n" +
	"\x18TransitionCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12E\n" +
	"\n" +
	"transition\x18\x02 \x01(\x0e2%.openctem.sensor.v3.CommandTransitionR\n" +
	"transition\x12$\n" +
	"\vlease_epoch\x18\x03 \x01(\x03H\x00R\n" +
	"leaseEpoch\x88\x01\x01\x12\x1b\n" +
	"\tbody_json\x18\x04 \x01(\fR\bbodyJsonB\x0e\n" +
	"\f_lease_epoch\">\n" +
	"\x19TransitionCommandResponse\x12!\n" +
	"\fcommand_json\x18\x01 \x01(\fR\vcommandJson\"V\n" +
	"\x18AppendCommandLogsRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tbody_json\x18\x02 \x01(\fR\bbodyJson\"@\n" +
	"\x19AppendCommandLogsResponse\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\fR\fresponseJson\"\x88\x02\n" +
	"\x10PutResultRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1d\n" +
	"\asegment\x18\x03 \x01(\rH\x00R\asegment\x88\x01\x01\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12)\n" +
	"\x10content_encoding\x18\x06 \x01(\tR\x0fcontentEncoding\x12%\n" +
	"\x0econtent_digest\x18\a \x01(\tR\rcontentDigestB\n" +
	"\n" +
	"\b_segment\"~\n" +
	"\x11PutResultResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12\x1f\n" +
	"\vstatus_json\x18\x02 \x01(\fR\n" +
	"statusJson\x12.\n" +
	"\x13retry_after_seconds\x18\x03 \x01(\x05R\x11retryAfterSeconds\"n\n" +
	"\x13CommitResultRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tbody_json\x18\x03 \x01(\fR\bbodyJson\"\x81\x01\n" +
	"\x14CommitResultResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12\x1f\n" +
	"\vstatus_json\x18\x02 \x01(\fR\n" +
	"statusJson\x12.\n" +
	"\x13retry_after_seconds\x18\x03 \x01(\x05R\x11retryAfterSeconds\"5\n" +
	"\x16GetResultStatusRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"j\n" +
	"\x17GetResultStatusResponse\x12\x1f\n" +
	"\vstatus_json\x18\x01 \x01(\fR\n" +
	"statusJson\x12.\n" +
	"\x13retry_after_seconds\x18\x02 \x01(\x05R\x11retryAfterSeconds\"3\n" +
	"\x14AbandonResultRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"\x17\n" +
	"\x15AbandonResultResponse\"9\n" +
	"\x12PutManifestRequest\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\fR\fmanifestJson\":\n" +
	"\x13PutManifestResponse\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\fR\fresponseJson\"\x14\n" +
	"\x12GetManifestRequest\":\n" +
	"\x13GetManifestResponse\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\fR\fresponseJson\"9\n" +
	"\x16PutConfigReportRequest\x12\x1f\n" +
	"\vreport_json\x18\x01 \x01(\fR\n" +
	"reportJson\">\n" +
	"\x17PutConfigReportResponse\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\fR\fresponseJson\",\n" +
	"\x16GetSuppressionsRequest\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\"}\n" +
	"\x17GetSuppressionsResponse\x12!\n" +
	"\fnot_modified\x18\x01 \x01(\bR\vnotModified\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12+\n" +
	"\x11suppressions_json\x18\x03 \x01(\fR\x10suppressionsJson\"=\n" +
	"\x18CheckFingerprintsRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\"@\n" +
	"\x19CheckFingerprintsResponse\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\fR\fresponseJson\"8\n" +
	"\x13BaselineDiffRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\";\n" +
	"\x14BaselineDiffResponse\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\fR\fresponseJson\"\x19\n" +
	"\x17IssueCertificateRequest\"\xc8\x02\n" +
	"\x18IssueCertificateResponse\x122\n" +
	"\x15certificate_chain_pem\x18\x01 \x01(\tR\x13certificateChainPem\x12\"\n" +
	"\rca_bundle_pem\x18\x02 \x01(\tR\vcaBundlePem\x129\n" +
	"\n" +
	"not_before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12;\n" +
	"\vrenew_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"renewAfter\x12#\n" +
	"\rgrpc_endpoint\x18\x06 \x01(\tR\fgrpcEndpoint*W\n" +
	"\aBinding\x12\x17\n" +
	"\x13BINDING_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fBINDING_GRPC\x10\x01\x12\x11\n" +
	"\rBINDING_HTTPS\x10\x02\x12\x0e\n" +
	"\n" +
	"BINDING_V2\x10\x03*\xd1\x01\n" +
	"\x11CommandTransition\x12\"\n" +
	"\x1eCOMMAND_TRANSITION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18COMMAND_TRANSITION_CLAIM\x10\x01\x12\x1c\n" +
	"\x18COMMAND_TRANSITION_START\x10\x02\x12\x1f\n" +
	"\x1bCOMMAND_TRANSITION_COMPLETE\x10\x03\x12\x1b\n" +
	"\x17COMMAND_TRANSITION_FAIL\x10\x04\x12\x1e\n" +
	"\x1aCOMMAND_TRANSITION_RELEASE\x10\x052\xff\r\n" +
	"\rSensorService\x12Q\n" +
	"\x05Hello\x12 .openctem.sensor.v3.HelloRequest\x1a!.openctem.sensor.v3.HelloResponse\"\x03\x90\x02\x01\x12X\n" +
	"\tHeartbeat\x12$.openctem.sensor.v3.HeartbeatRequest\x1a%.openctem.sensor.v3.HeartbeatResponse\x12Z\n" +
	"\tSubscribe\x12$.openctem.sensor.v3.SubscribeRequest\x1a%.openctem.sensor.v3.SubscribeResponse0\x01\x12d\n" +
	"\rClaimCommands\x12(.openctem.sensor.v3.ClaimCommandsRequest\x1a).openctem.sensor.v3.ClaimCommandsResponse\x12p\n" +
	"\x11TransitionCommand\x12,.openctem.sensor.v3.TransitionCommandRequest\x1a-.openctem.sensor.v3.TransitionCommandResponse\x12p\n" +
	"\x11AppendCommandLogs\x12,.openctem.sensor.v3.AppendCommandLogsRequest\x1a-.openctem.sensor.v3.AppendCommandLogsResponse\x12]\n" +
	"\tPutResult\x12$.openctem.sensor.v3.PutResultRequest\x1a%.openctem.sensor.v3.PutResultResponse\"\x03\x90\x02\x02\x12f\n" +
	"\fCommitResult\x12'.openctem.sensor.v3.CommitResultRequest\x1a(.openctem.sensor.v3.CommitResultResponse\"\x03\x90\x02\x02\x12o\n" +
	"\x0fGetResultStatus\x12*.openctem.sensor.v3.GetResultStatusRequest\x1a+.openctem.sensor.v3.GetResultStatusResponse\"\x03\x90\x02\x01\x12i\n" +
	"\rAbandonResult\x12(.openctem.sensor.v3.AbandonResultRequest\x1a).openctem.sensor.v3.AbandonResultResponse\"\x03\x90\x02\x02\x12c\n" +
	"\vPutManifest\x12&.openctem.sensor.v3.PutManifestRequest\x1a'.openctem.sensor.v3.PutManifestResponse\"\x03\x90\x02\x02\x12c\n" +
	"\vGetManifest\x12&.openctem.sensor.v3.GetManifestRequest\x1a'.openctem.sensor.v3.GetManifestResponse\"\x03\x90\x02\x01\x12o\n" +
	"\x0fPutConfigReport\x12*.openctem.sensor.v3.PutConfigReportRequest\x1a+.openctem.sensor.v3.PutConfigReportResponse\"\x03\x90\x02\x02\x12o\n" +
	"\x0fGetSuppressions\x12*.openctem.sensor.v3.GetSuppressionsRequest\x1a+.openctem.sensor.v3.GetSuppressionsResponse\"\x03\x90\x02\x01\x12u\n" +
	"\x11CheckFingerprints\x12,.openctem.sensor.v3.CheckFingerprintsRequest\x1a-.openctem.sensor.v3.CheckFingerprintsResponse\"\x03\x90\x02\x01\x12f\n" +
	"\fBaselineDiff\x12'.openctem.sensor.v3.BaselineDiffRequest\x1a(.openctem.sensor.v3.BaselineDiffResponse\"\x03\x90\x02\x01\x12m\n" +
	"\x10IssueCertificate\x12+.openctem.sensor.v3.IssueCertificateRequest\x1a,.openctem.sensor.v3.IssueCertificateResponseB\xc9\x01\n" +
	"\x16com.openctem.sensor.v3B\vSensorProtoP\x01Z8github.com/openctemio/sdk-go/pkg/sensorproto/v3;sensorv3\xa2\x02\x03OSX\xaa\x02\x12Openctem.Sensor.V3\xca\x02\x12Openctem\\Sensor\\V3\xe2\x02\x1eOpenctem\\Sensor\\V3\\GPBMetadata\xea\x02\x14Openctem::Sensor::V3b\x06proto3"

var (
	file_openctem_sensor_v3_sensor_proto_rawDescOnce sync.Once
	file_openctem_sensor_v3_sensor_proto_rawDescData []byte
)

func file_openctem_sensor_v3_sensor_proto_rawDescGZIP() []byte {
	file_openctem_sensor_v3_sensor_proto_rawDescOnce.Do(func() {
		file_openctem_sensor_v3_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openctem_sensor_v3_sensor_proto_rawDesc), len(file_openctem_sensor_v3_sensor_proto_rawDesc)))
	})
	return file_openctem_sensor_v3_sensor_proto_rawDescData
}

var file_openctem_sensor_v3_sensor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_openctem_sensor_v3_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_openctem_sensor_v3_sensor_proto_goTypes = []any{
	(Binding)(0),                      // 0: openctem.sensor.v3.Binding
	(CommandTransition)(0),            // 1: openctem.sensor.v3.CommandTransition
	(*Problem)(nil),                   // 2: openctem.sensor.v3.Problem
	(*Transport)(nil),                 // 3: openctem.sensor.v3.Transport
	(*HelloRequest)(nil),              // 4: openctem.sensor.v3.HelloRequest
	(*HelloResponse)(nil),             // 5: openctem.sensor.v3.HelloResponse
	(*HeartbeatRequest)(nil),          // 6: openctem.sensor.v3.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 7: openctem.sensor.v3.HeartbeatResponse
	(*SubscribeRequest)(nil),          // 8: openctem.sensor.v3.SubscribeRequest
	(*SubscribeResponse)(nil),         // 9: openctem.sensor.v3.SubscribeResponse
	(*ClaimCommandsRequest)(nil),      // 10: openctem.sensor.v3.ClaimCommandsRequest
	(*ClaimCommandsResponse)(nil),     // 11: openctem.sensor.v3.ClaimCommandsResponse
	(*TransitionCommandRequest)(nil),  // 12: openctem.sensor.v3.TransitionCommandRequest
	(*TransitionCommandResponse)(nil), // 13: openctem.sensor.v3.TransitionCommandResponse
	(*AppendCommandLogsRequest)(nil),  // 14: openctem.sensor.v3.AppendCommandLogsRequest
	(*AppendCommandLogsResponse)(nil), // 15: openctem.sensor.v3.AppendCommandLogsResponse
	(*PutResultRequest)(nil),          // 16: openctem.sensor.v3.PutResultRequest
	(*PutResultResponse)(nil),         // 17: openctem.sensor.v3.PutResultResponse
	(*CommitResultRequest)(nil),       // 18: openctem.sensor.v3.CommitResultRequest
	(*CommitResultResponse)(nil),      // 19: openctem.sensor.v3.CommitResultResponse
	(*GetResultStatusRequest)(nil),    // 20: openctem.sensor.v3.GetResultStatusRequest
	(*GetResultStatusResponse)(nil),   // 21: openctem.sensor.v3.GetResultStatusResponse
	(*AbandonResultRequest)(nil),      // 22: openctem.sensor.v3.AbandonResultRequest
	(*AbandonResultResponse)(nil),     // 23: openctem.sensor.v3.AbandonResultResponse
	(*PutManifestRequest)(nil),        // 24: openctem.sensor.v3.PutManifestRequest
	(*PutManifestResponse)(nil),       // 25: openctem.sensor.v3.PutManifestResponse
	(*GetManifestRequest)(nil),        // 26: openctem.sensor.v3.GetManifestRequest
	(*GetManifestResponse)(nil),       // 27: openctem.sensor.v3.GetManifestResponse
	(*PutConfigReportRequest)(nil),    // 28: openctem.sensor.v3.PutConfigReportRequest
	(*PutConfigReportResponse)(nil),   // 29: openctem.sensor.v3.PutConfigReportResponse
	(*GetSuppressionsRequest)(nil),    // 30: openctem.sensor.v3.GetSuppressionsRequest
	(*GetSuppressionsResponse)(nil),   // 31: openctem.sensor.v3.GetSuppressionsResponse
	(*CheckFingerprintsRequest)(nil),  // 32: openctem.sensor.v3.CheckFingerprintsRequest
	(*CheckFingerprintsResponse)(nil), // 33: openctem.sensor.v3.CheckFingerprintsResponse
	(*BaselineDiffRequest)(nil),       // 34: openctem.sensor.v3.BaselineDiffRequest
	(*BaselineDiffResponse)(nil),      // 35: openctem.sensor.v3.BaselineDiffResponse
	(*IssueCertificateRequest)(nil),   // 36: openctem.sensor.v3.IssueCertificateRequest
	(*IssueCertificateResponse)(nil),  // 37: openctem.sensor.v3.IssueCertificateResponse
	(*timestamppb.Timestamp)(nil),     // 38: google.protobuf.Timestamp
}
var file_openctem_sensor_v3_sensor_proto_depIdxs = []int32{
	0,  // 0: openctem.sensor.v3.Transport.binding:type_name -> openctem.sensor.v3.Binding
	38, // 1: openctem.sensor.v3.Transport.since:type_name -> google.protobuf.Timestamp
	0,  // 2: openctem.sensor.v3.HelloResponse.binding:type_name -> openctem.sensor.v3.Binding
	3,  // 3: openctem.sensor.v3.HeartbeatRequest.transport:type_name -> openctem.sensor.v3.Transport
	1,  // 4: openctem.sensor.v3.TransitionCommandRequest.transition:type_name -> openctem.sensor.v3.CommandTransition
	38, // 5: openctem.sensor.v3.IssueCertificateResponse.not_before:type_name -> google.protobuf.Timestamp
	38, // 6: openctem.sensor.v3.IssueCertificateResponse.not_after:type_name -> google.protobuf.Timestamp
	38, // 7: openctem.sensor.v3.IssueCertificateResponse.renew_after:type_name -> google.protobuf.Timestamp
	4,  // 8: openctem.sensor.v3.SensorService.Hello:input_type -> openctem.sensor.v3.HelloRequest
	6,  // 9: openctem.sensor.v3.SensorService.Heartbeat:input_type -> openctem.sensor.v3.HeartbeatRequest
	8,  // 10: openctem.sensor.v3.SensorService.Subscribe:input_type -> openctem.sensor.v3.SubscribeRequest
	10, // 11: openctem.sensor.v3.SensorService.ClaimCommands:input_type -> openctem.sensor.v3.ClaimCommandsRequest
	12, // 12: openctem.sensor.v3.SensorService.TransitionCommand:input_type -> openctem.sensor.v3.TransitionCommandRequest
	14, // 13: openctem.sensor.v3.SensorService.AppendCommandLogs:input_type -> openctem.sensor.v3.AppendCommandLogsRequest
	16, // 14: openctem.sensor.v3.SensorService.PutResult:input_type -> openctem.sensor.v3.PutResultRequest
	18, // 15: openctem.sensor.v3.SensorService.CommitResult:input_type -> openctem.sensor.v3.CommitResultRequest
	20, // 16: openctem.sensor.v3.SensorService.GetResultStatus:input_type -> openctem.sensor.v3.GetResultStatusRequest
	22, // 17: openctem.sensor.v3.SensorService.AbandonResult:input_type -> openctem.sensor.v3.AbandonResultRequest
	24, // 18: openctem.sensor.v3.SensorService.PutManifest:input_type -> openctem.sensor.v3.PutManifestRequest
	26, // 19: openctem.sensor.v3.SensorService.GetManifest:input_type -> openctem.sensor.v3.GetManifestRequest
	28, // 20: openctem.sensor.v3.SensorService.PutConfigReport:input_type -> openctem.sensor.v3.PutConfigReportRequest
	30, // 21: openctem.sensor.v3.SensorService.GetSuppressions:input_type -> openctem.sensor.v3.GetSuppressionsRequest
	32, // 22: openctem.sensor.v3.SensorService.CheckFingerprints:input_type -> openctem.sensor.v3.CheckFingerprintsRequest
	34, // 23: openctem.sensor.v3.SensorService.BaselineDiff:input_type -> openctem.sensor.v3.BaselineDiffRequest
	36, // 24: openctem.sensor.v3.SensorService.IssueCertificate:input_type -> openctem.sensor.v3.IssueCertificateRequest
	5,  // 25: openctem.sensor.v3.SensorService.Hello:output_type -> openctem.sensor.v3.HelloResponse
	7,  // 26: openctem.sensor.v3.SensorService.Heartbeat:output_type -> openctem.sensor.v3.HeartbeatResponse
	9,  // 27: openctem.sensor.v3.SensorService.Subscribe:output_type -> openctem.sensor.v3.SubscribeResponse
	11, // 28: openctem.sensor.v3.SensorService.ClaimCommands:output_type -> openctem.sensor.v3.ClaimCommandsResponse
	13, // 29: openctem.sensor.v3.SensorService.TransitionCommand:output_type -> openctem.sensor.v3.TransitionCommandResponse
	15, // 30: openctem.sensor.v3.SensorService.AppendCommandLogs:output_type -> openctem.sensor.v3.AppendCommandLogsResponse
	17, // 31: openctem.sensor.v3.SensorService.PutResult:output_type -> openctem.sensor.v3.PutResultResponse
	19, // 32: openctem.sensor.v3.SensorService.CommitResult:output_type -> openctem.sensor.v3.CommitResultResponse
	21, // 33: openctem.sensor.v3.SensorService.GetResultStatus:output_type -> openctem.sensor.v3.GetResultStatusResponse
	23, // 34: openctem.sensor.v3.SensorService.AbandonResult:output_type -> openctem.sensor.v3.AbandonResultResponse
	25, // 35: openctem.sensor.v3.SensorService.PutManifest:output_type -> openctem.sensor.v3.PutManifestResponse
	27, // 36: openctem.sensor.v3.SensorService.GetManifest:output_type -> openctem.sensor.v3.GetManifestResponse
	29, // 37: openctem.sensor.v3.SensorService.PutConfigReport:output_type -> openctem.sensor.v3.PutConfigReportResponse
	31, // 38: openctem.sensor.v3.SensorService.GetSuppressions:output_type -> openctem.sensor.v3.GetSuppressionsResponse
	33, // 39: openctem.sensor.v3.SensorService.CheckFingerprints:output_type -> openctem.sensor.v3.CheckFingerprintsResponse
	35, // 40: openctem.sensor.v3.SensorService.BaselineDiff:output_type -> openctem.sensor.v3.BaselineDiffResponse
	37, // 41: openctem.sensor.v3.SensorService.IssueCertificate:output_type -> openctem.sensor.v3.IssueCertificateResponse
	25, // [25:42] is the sub-list for method output_type
	8,  // [8:25] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_openctem_sensor_v3_sensor_proto_init() }
func file_openctem_sensor_v3_sensor_proto_init() {
	if File_openctem_sensor_v3_sensor_proto != nil {
		return
	}
	file_openctem_sensor_v3_sensor_proto_msgTypes[10].OneofWrappers = []any{}
	file_openctem_sensor_v3_sensor_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openctem_sensor_v3_sensor_proto_rawDesc), len(file_openctem_sensor_v3_sensor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openctem_sensor_v3_sensor_proto_goTypes,
		DependencyIndexes: file_openctem_sensor_v3_sensor_proto_depIdxs,
		EnumInfos:         file_openctem_sensor_v3_sensor_proto_enumTypes,
		MessageInfos:      file_openctem_sensor_v3_sensor_proto_msgTypes,
	}.Build()
	File_openctem_sensor_v3_sensor_proto = out.File
	file_openctem_sensor_v3_sensor_proto_goTypes = nil
	file_openctem_sensor_v3_sensor_proto_depIdxs = nil
}
