// Code generated by genalias from github.com/openctemio/ctis v1.2.1-0.20261004040853-1f96790f7a6f; DO NOT EDIT.

package ctis

import upstream "github.com/openctemio/ctis"

// Types: every exported type of github.com/openctemio/ctis.
type (
	Dependency               = upstream.Dependency
	DependencyLocation       = upstream.DependencyLocation
	ReconConverterOptions    = upstream.ReconConverterOptions
	ReconToCTISInput         = upstream.ReconToCTISInput
	SubdomainInput           = upstream.SubdomainInput
	DNSRecordInput           = upstream.DNSRecordInput
	OpenPortInput            = upstream.OpenPortInput
	LiveHostInput            = upstream.LiveHostInput
	DiscoveredURLInput       = upstream.DiscoveredURLInput
	TechnologyInput          = upstream.TechnologyInput
	SARIFTool                = upstream.SARIFTool
	SARIFDriver              = upstream.SARIFDriver
	SARIFRule                = upstream.SARIFRule
	SARIFRuleConfig          = upstream.SARIFRuleConfig
	SARIFResult              = upstream.SARIFResult
	SARIFReportingReference  = upstream.SARIFReportingReference
	SARIFMessage             = upstream.SARIFMessage
	SARIFLocation            = upstream.SARIFLocation
	SARIFLogicalLocation     = upstream.SARIFLogicalLocation
	SARIFPhysicalLocation    = upstream.SARIFPhysicalLocation
	SARIFArtifactLocation    = upstream.SARIFArtifactLocation
	SARIFRegion              = upstream.SARIFRegion
	SARIFSnippet             = upstream.SARIFSnippet
	SARIFArtifact            = upstream.SARIFArtifact
	SARIFInvocation          = upstream.SARIFInvocation
	ConvertOptions           = upstream.ConvertOptions
	Report                   = upstream.Report
	ReportMetadata           = upstream.ReportMetadata
	BranchInfo               = upstream.BranchInfo
	Scope                    = upstream.Scope
	Tool                     = upstream.Tool
	Asset                    = upstream.Asset
	AssetIdentifiers         = upstream.AssetIdentifiers
	AssetCompliance          = upstream.AssetCompliance
	ServiceInfo              = upstream.ServiceInfo
	AssetTechnical           = upstream.AssetTechnical
	DomainTechnical          = upstream.DomainTechnical
	DNSRecord                = upstream.DNSRecord
	IPAddressTechnical       = upstream.IPAddressTechnical
	PortInfo                 = upstream.PortInfo
	Geolocation              = upstream.Geolocation
	RepositoryTechnical      = upstream.RepositoryTechnical
	CertificateTechnical     = upstream.CertificateTechnical
	CloudTechnical           = upstream.CloudTechnical
	ServiceTechnical         = upstream.ServiceTechnical
	Web3Technical            = upstream.Web3Technical
	SmartContractDetails     = upstream.SmartContractDetails
	ContractLibrary          = upstream.ContractLibrary
	WalletDetails            = upstream.WalletDetails
	TokenBalance             = upstream.TokenBalance
	TokenDetails             = upstream.TokenDetails
	TradingPair              = upstream.TradingPair
	DeFiDetails              = upstream.DeFiDetails
	CoreContract             = upstream.CoreContract
	AuditReport              = upstream.AuditReport
	NFTCollectionDetails     = upstream.NFTCollectionDetails
	Finding                  = upstream.Finding
	FindingExposure          = upstream.FindingExposure
	RemediationContext       = upstream.RemediationContext
	BusinessImpact           = upstream.BusinessImpact
	FindingStatus            = upstream.FindingStatus
	DataFlow                 = upstream.DataFlow
	DataFlowLocation         = upstream.DataFlowLocation
	DataFlowLocationType     = upstream.DataFlowLocationType
	StackTrace               = upstream.StackTrace
	StackFrame               = upstream.StackFrame
	Attachment               = upstream.Attachment
	ArtifactLocation         = upstream.ArtifactLocation
	Suppression              = upstream.Suppression
	FindingLocation          = upstream.FindingLocation
	NetworkLocation          = upstream.NetworkLocation
	LogicalLocation          = upstream.LogicalLocation
	VulnerabilityDetails     = upstream.VulnerabilityDetails
	VulnDataSource           = upstream.VulnDataSource
	ASVSInfo                 = upstream.ASVSInfo
	ContainerLayer           = upstream.ContainerLayer
	SecretDetails            = upstream.SecretDetails
	MisconfigurationDetails  = upstream.MisconfigurationDetails
	ComplianceDetails        = upstream.ComplianceDetails
	Web3VulnerabilityDetails = upstream.Web3VulnerabilityDetails
	Web3POC                  = upstream.Web3POC
	GasIssue                 = upstream.GasIssue
	AccessControlIssue       = upstream.AccessControlIssue
	ReentrancyIssue          = upstream.ReentrancyIssue
	OracleManipulationIssue  = upstream.OracleManipulationIssue
	FlashLoanIssue           = upstream.FlashLoanIssue
	Web3VulnerabilityClass   = upstream.Web3VulnerabilityClass
	Remediation              = upstream.Remediation
	FixRegex                 = upstream.FixRegex
	AssetType                = upstream.AssetType
	FindingType              = upstream.FindingType
	Severity                 = upstream.Severity
	Criticality              = upstream.Criticality
	Properties               = upstream.Properties
)

// Constants.
const (
	FindingStatusOpen             = upstream.FindingStatusOpen
	FindingStatusResolved         = upstream.FindingStatusResolved
	FindingStatusSuppressed       = upstream.FindingStatusSuppressed
	FindingStatusFalsePositive    = upstream.FindingStatusFalsePositive
	FindingStatusAcceptedRisk     = upstream.FindingStatusAcceptedRisk
	FindingStatusInProgress       = upstream.FindingStatusInProgress
	DataFlowLocationSource        = upstream.DataFlowLocationSource
	DataFlowLocationSink          = upstream.DataFlowLocationSink
	DataFlowLocationPropagator    = upstream.DataFlowLocationPropagator
	DataFlowLocationSanitizer     = upstream.DataFlowLocationSanitizer
	DataFlowLocationTransform     = upstream.DataFlowLocationTransform
	Web3VulnReentrancy            = upstream.Web3VulnReentrancy
	Web3VulnIntegerOverflow       = upstream.Web3VulnIntegerOverflow
	Web3VulnIntegerUnderflow      = upstream.Web3VulnIntegerUnderflow
	Web3VulnAccessControl         = upstream.Web3VulnAccessControl
	Web3VulnUncheckedCall         = upstream.Web3VulnUncheckedCall
	Web3VulnDelegateCall          = upstream.Web3VulnDelegateCall
	Web3VulnSelfDestruct          = upstream.Web3VulnSelfDestruct
	Web3VulnTxOrigin              = upstream.Web3VulnTxOrigin
	Web3VulnTimestampDependence   = upstream.Web3VulnTimestampDependence
	Web3VulnBlockHashDependence   = upstream.Web3VulnBlockHashDependence
	Web3VulnFlashLoan             = upstream.Web3VulnFlashLoan
	Web3VulnOracleManipulation    = upstream.Web3VulnOracleManipulation
	Web3VulnFrontRunning          = upstream.Web3VulnFrontRunning
	Web3VulnSandwichAttack        = upstream.Web3VulnSandwichAttack
	Web3VulnSlippage              = upstream.Web3VulnSlippage
	Web3VulnPriceManipulation     = upstream.Web3VulnPriceManipulation
	Web3VulnGovernanceAttack      = upstream.Web3VulnGovernanceAttack
	Web3VulnLiquidityDrain        = upstream.Web3VulnLiquidityDrain
	Web3VulnMEV                   = upstream.Web3VulnMEV
	Web3VulnHoneypot              = upstream.Web3VulnHoneypot
	Web3VulnHiddenMint            = upstream.Web3VulnHiddenMint
	Web3VulnHiddenFee             = upstream.Web3VulnHiddenFee
	Web3VulnBlacklistAbuse        = upstream.Web3VulnBlacklistAbuse
	Web3VulnRenounceOwnership     = upstream.Web3VulnRenounceOwnership
	Web3VulnStorageCollision      = upstream.Web3VulnStorageCollision
	Web3VulnUninitializedProxy    = upstream.Web3VulnUninitializedProxy
	Web3VulnUpgradeVuln           = upstream.Web3VulnUpgradeVuln
	Web3VulnWeakRandomness        = upstream.Web3VulnWeakRandomness
	Web3VulnSignatureMalleability = upstream.Web3VulnSignatureMalleability
	Web3VulnReplayAttack          = upstream.Web3VulnReplayAttack
	Web3VulnDosGasLimit           = upstream.Web3VulnDosGasLimit
	Web3VulnUnboundedLoop         = upstream.Web3VulnUnboundedLoop
	Web3VulnDosBlockStuffing      = upstream.Web3VulnDosBlockStuffing
	Web3VulnBusinessLogic         = upstream.Web3VulnBusinessLogic
	Web3VulnInvariantViolation    = upstream.Web3VulnInvariantViolation
	AssetTypeDomain               = upstream.AssetTypeDomain
	AssetTypeSubdomain            = upstream.AssetTypeSubdomain
	AssetTypeIPAddress            = upstream.AssetTypeIPAddress
	AssetTypeCertificate          = upstream.AssetTypeCertificate
	AssetTypeWebsite              = upstream.AssetTypeWebsite
	AssetTypeWebApplication       = upstream.AssetTypeWebApplication
	AssetTypeAPI                  = upstream.AssetTypeAPI
	AssetTypeMobileApp            = upstream.AssetTypeMobileApp
	AssetTypeService              = upstream.AssetTypeService
	AssetTypeRepository           = upstream.AssetTypeRepository
	AssetTypeCloudAccount         = upstream.AssetTypeCloudAccount
	AssetTypeCompute              = upstream.AssetTypeCompute
	AssetTypeStorage              = upstream.AssetTypeStorage
	AssetTypeDatabase             = upstream.AssetTypeDatabase
	AssetTypeServerless           = upstream.AssetTypeServerless
	AssetTypeContainerRegistry    = upstream.AssetTypeContainerRegistry
	AssetTypeHost                 = upstream.AssetTypeHost
	AssetTypeServer               = upstream.AssetTypeServer
	AssetTypeContainer            = upstream.AssetTypeContainer
	AssetTypeKubernetes           = upstream.AssetTypeKubernetes
	AssetTypeKubernetesCluster    = upstream.AssetTypeKubernetesCluster
	AssetTypeKubernetesNamespace  = upstream.AssetTypeKubernetesNamespace
	AssetTypeNetwork              = upstream.AssetTypeNetwork
	AssetTypeVPC                  = upstream.AssetTypeVPC
	AssetTypeSubnet               = upstream.AssetTypeSubnet
	AssetTypeLoadBalancer         = upstream.AssetTypeLoadBalancer
	AssetTypeFirewall             = upstream.AssetTypeFirewall
	AssetTypeIAMUser              = upstream.AssetTypeIAMUser
	AssetTypeIAMRole              = upstream.AssetTypeIAMRole
	AssetTypeServiceAccount       = upstream.AssetTypeServiceAccount
	AssetTypeHTTPService          = upstream.AssetTypeHTTPService
	AssetTypeOpenPort             = upstream.AssetTypeOpenPort
	AssetTypeDiscoveredURL        = upstream.AssetTypeDiscoveredURL
	AssetTypeSmartContract        = upstream.AssetTypeSmartContract
	AssetTypeWallet               = upstream.AssetTypeWallet
	AssetTypeNFTCollection        = upstream.AssetTypeNFTCollection
	AssetTypeDeFiProtocol         = upstream.AssetTypeDeFiProtocol
	AssetTypeToken                = upstream.AssetTypeToken
	AssetTypeBlockchain           = upstream.AssetTypeBlockchain
	AssetTypeUnclassified         = upstream.AssetTypeUnclassified
	FindingTypeVulnerability      = upstream.FindingTypeVulnerability
	FindingTypeSecret             = upstream.FindingTypeSecret
	FindingTypeMisconfiguration   = upstream.FindingTypeMisconfiguration
	FindingTypeCompliance         = upstream.FindingTypeCompliance
	FindingTypeWeb3               = upstream.FindingTypeWeb3
	SeverityCritical              = upstream.SeverityCritical
	SeverityHigh                  = upstream.SeverityHigh
	SeverityMedium                = upstream.SeverityMedium
	SeverityLow                   = upstream.SeverityLow
	SeverityInfo                  = upstream.SeverityInfo
	CriticalityCritical           = upstream.CriticalityCritical
	CriticalityHigh               = upstream.CriticalityHigh
	CriticalityMedium             = upstream.CriticalityMedium
	CriticalityLow                = upstream.CriticalityLow
	CriticalityInfo               = upstream.CriticalityInfo
	SchemaVersion                 = upstream.SchemaVersion
	SchemaMajor                   = upstream.SchemaMajor
	SchemaBaseURL                 = upstream.SchemaBaseURL
	SchemaURL                     = upstream.SchemaURL
)

// NormalizeAssetName calls github.com/openctemio/ctis.NormalizeAssetName.
func NormalizeAssetName(assetType AssetType, name string) string {
	return upstream.NormalizeAssetName(assetType, name)
}

// DefaultReconConverterOptions calls github.com/openctemio/ctis.DefaultReconConverterOptions.
func DefaultReconConverterOptions() *ReconConverterOptions {
	return upstream.DefaultReconConverterOptions()
}

// ConvertReconToCTIS calls github.com/openctemio/ctis.ConvertReconToCTIS.
func ConvertReconToCTIS(input *ReconToCTISInput, opts *ReconConverterOptions) (*Report, error) {
	return upstream.ConvertReconToCTIS(input, opts)
}

// MergeReconReports calls github.com/openctemio/ctis.MergeReconReports.
func MergeReconReports(reports []*Report) *Report {
	return upstream.MergeReconReports(reports)
}

// DefaultConvertOptions calls github.com/openctemio/ctis.DefaultConvertOptions.
func DefaultConvertOptions() *ConvertOptions {
	return upstream.DefaultConvertOptions()
}

// AllFindingStatuses calls github.com/openctemio/ctis.AllFindingStatuses.
func AllFindingStatuses() []FindingStatus {
	return upstream.AllFindingStatuses()
}

// AllDataFlowLocationTypes calls github.com/openctemio/ctis.AllDataFlowLocationTypes.
func AllDataFlowLocationTypes() []DataFlowLocationType {
	return upstream.AllDataFlowLocationTypes()
}

// AllWeb3VulnerabilityClasses calls github.com/openctemio/ctis.AllWeb3VulnerabilityClasses.
func AllWeb3VulnerabilityClasses() []Web3VulnerabilityClass {
	return upstream.AllWeb3VulnerabilityClasses()
}

// AllAssetTypes calls github.com/openctemio/ctis.AllAssetTypes.
func AllAssetTypes() []AssetType {
	return upstream.AllAssetTypes()
}

// AllFindingTypes calls github.com/openctemio/ctis.AllFindingTypes.
func AllFindingTypes() []FindingType {
	return upstream.AllFindingTypes()
}

// AllSeverities calls github.com/openctemio/ctis.AllSeverities.
func AllSeverities() []Severity {
	return upstream.AllSeverities()
}

// AllCriticalities calls github.com/openctemio/ctis.AllCriticalities.
func AllCriticalities() []Criticality {
	return upstream.AllCriticalities()
}

// NewReport calls github.com/openctemio/ctis.NewReport.
func NewReport() *Report {
	return upstream.NewReport()
}

// NewDataFlow calls github.com/openctemio/ctis.NewDataFlow.
func NewDataFlow(source, sink DataFlowLocation) *DataFlow {
	return upstream.NewDataFlow(source, sink)
}

// NewDataFlowLocation calls github.com/openctemio/ctis.NewDataFlowLocation.
func NewDataFlowLocation(path string, line, column int, content string) DataFlowLocation {
	return upstream.NewDataFlowLocation(path, line, column, content)
}

// ParseVersion calls github.com/openctemio/ctis.ParseVersion.
func ParseVersion(v string) (major, minor int, ok bool) {
	return upstream.ParseVersion(v)
}

// IsCompatibleVersion calls github.com/openctemio/ctis.IsCompatibleVersion.
func IsCompatibleVersion(v string) bool {
	return upstream.IsCompatibleVersion(v)
}
