// Sensor protocol v3: the sensor <-> platform transport
// (docs/rfcs/RFC-059-sensor-transport-v3.md).
//
// One service, two bindings served by the same handlers:
//   - gRPC over HTTP/2 on the dedicated sensor host, authenticated by a client
//     certificate from the sensor CA (mTLS, TLS 1.3);
//   - Connect over HTTPS (HTTP/1.1 or HTTP/2) under /api/v3/sensor on the
//     platform host, authenticated by an RFC 9421 request signature with the
//     sensor's key, as protocol v2.
//
// v3 carries the resource model of protocol v2 (RFC-026 results, RFC-029
// control plane). The envelope is typed: identifiers, sequence numbers, lease
// epochs, encodings, digests, entity tags and transport facts. A document whose
// schema is owned by another specification travels as its JSON bytes, unchanged:
// the heartbeat body and answer (RFC-029), commands (RFC-029), CTIS reports
// (RFC-026), the manifest (RFC-033), the config report and suppressions.
//
// Rules every message follows:
//   - No message names a tenant. The tenant and the sensor are those of the
//     authenticated identity (certificate or signature), never of a field.
//   - A command or report id of another sensor or tenant is NOT_FOUND.
//   - An error carries an openctem.sensor.v3.Problem detail: the RFC 9457
//     problem document v2 would have answered, with its HTTP status.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openctem/sensor/v3/sensor.proto

package sensorv3connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v3 "github.com/openctemio/sdk-go/pkg/sensorproto/v3"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SensorServiceName is the fully-qualified name of the SensorService service.
	SensorServiceName = "openctem.sensor.v3.SensorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SensorServiceHelloProcedure is the fully-qualified name of the SensorService's Hello RPC.
	SensorServiceHelloProcedure = "/openctem.sensor.v3.SensorService/Hello"
	// SensorServiceHeartbeatProcedure is the fully-qualified name of the SensorService's Heartbeat RPC.
	SensorServiceHeartbeatProcedure = "/openctem.sensor.v3.SensorService/Heartbeat"
	// SensorServiceSubscribeProcedure is the fully-qualified name of the SensorService's Subscribe RPC.
	SensorServiceSubscribeProcedure = "/openctem.sensor.v3.SensorService/Subscribe"
	// SensorServiceClaimCommandsProcedure is the fully-qualified name of the SensorService's
	// ClaimCommands RPC.
	SensorServiceClaimCommandsProcedure = "/openctem.sensor.v3.SensorService/ClaimCommands"
	// SensorServiceTransitionCommandProcedure is the fully-qualified name of the SensorService's
	// TransitionCommand RPC.
	SensorServiceTransitionCommandProcedure = "/openctem.sensor.v3.SensorService/TransitionCommand"
	// SensorServiceAppendCommandLogsProcedure is the fully-qualified name of the SensorService's
	// AppendCommandLogs RPC.
	SensorServiceAppendCommandLogsProcedure = "/openctem.sensor.v3.SensorService/AppendCommandLogs"
	// SensorServicePutResultProcedure is the fully-qualified name of the SensorService's PutResult RPC.
	SensorServicePutResultProcedure = "/openctem.sensor.v3.SensorService/PutResult"
	// SensorServiceCommitResultProcedure is the fully-qualified name of the SensorService's
	// CommitResult RPC.
	SensorServiceCommitResultProcedure = "/openctem.sensor.v3.SensorService/CommitResult"
	// SensorServiceGetResultStatusProcedure is the fully-qualified name of the SensorService's
	// GetResultStatus RPC.
	SensorServiceGetResultStatusProcedure = "/openctem.sensor.v3.SensorService/GetResultStatus"
	// SensorServiceAbandonResultProcedure is the fully-qualified name of the SensorService's
	// AbandonResult RPC.
	SensorServiceAbandonResultProcedure = "/openctem.sensor.v3.SensorService/AbandonResult"
	// SensorServicePutManifestProcedure is the fully-qualified name of the SensorService's PutManifest
	// RPC.
	SensorServicePutManifestProcedure = "/openctem.sensor.v3.SensorService/PutManifest"
	// SensorServiceGetManifestProcedure is the fully-qualified name of the SensorService's GetManifest
	// RPC.
	SensorServiceGetManifestProcedure = "/openctem.sensor.v3.SensorService/GetManifest"
	// SensorServicePutConfigReportProcedure is the fully-qualified name of the SensorService's
	// PutConfigReport RPC.
	SensorServicePutConfigReportProcedure = "/openctem.sensor.v3.SensorService/PutConfigReport"
	// SensorServiceGetSuppressionsProcedure is the fully-qualified name of the SensorService's
	// GetSuppressions RPC.
	SensorServiceGetSuppressionsProcedure = "/openctem.sensor.v3.SensorService/GetSuppressions"
	// SensorServiceCheckFingerprintsProcedure is the fully-qualified name of the SensorService's
	// CheckFingerprints RPC.
	SensorServiceCheckFingerprintsProcedure = "/openctem.sensor.v3.SensorService/CheckFingerprints"
	// SensorServiceBaselineDiffProcedure is the fully-qualified name of the SensorService's
	// BaselineDiff RPC.
	SensorServiceBaselineDiffProcedure = "/openctem.sensor.v3.SensorService/BaselineDiff"
	// SensorServiceIssueCertificateProcedure is the fully-qualified name of the SensorService's
	// IssueCertificate RPC.
	SensorServiceIssueCertificateProcedure = "/openctem.sensor.v3.SensorService/IssueCertificate"
)

// SensorServiceClient is a client for the openctem.sensor.v3.SensorService service.
type SensorServiceClient interface {
	// Hello returns the protocol level, the features and limits this platform
	// serves and where its v3 endpoints are.
	Hello(context.Context, *connect.Request[v3.HelloRequest]) (*connect.Response[v3.HelloResponse], error)
	// Heartbeat records the sensor's state and answers with the doorbell
	// (RFC-029 §4.3, RFC-035).
	Heartbeat(context.Context, *connect.Request[v3.HeartbeatRequest]) (*connect.Response[v3.HeartbeatResponse], error)
	// Subscribe is the control stream: the platform pushes the doorbell (work
	// waiting, cancels, pause, drain, key rotation, manifest requests) as soon as
	// it changes, plus a keepalive. It never carries a job: jobs are claimed with
	// ClaimCommands, so the database lease stays the only source of truth and a
	// lost stream loses nothing.
	Subscribe(context.Context, *connect.Request[v3.SubscribeRequest]) (*connect.ServerStreamForClient[v3.SubscribeResponse], error)
	// ClaimCommands claims up to limit commands this sensor may run now.
	ClaimCommands(context.Context, *connect.Request[v3.ClaimCommandsRequest]) (*connect.Response[v3.ClaimCommandsResponse], error)
	// TransitionCommand moves a command this sensor holds: claim, start,
	// complete, fail or release (RFC-029, RFC-030 §5.12).
	TransitionCommand(context.Context, *connect.Request[v3.TransitionCommandRequest]) (*connect.Response[v3.TransitionCommandResponse], error)
	// AppendCommandLogs appends a batch of task log lines (RFC-029 §4.4.1).
	AppendCommandLogs(context.Context, *connect.Request[v3.AppendCommandLogsRequest]) (*connect.Response[v3.AppendCommandLogsResponse], error)
	// PutResult uploads a whole CTIS report, or one segment of it. Idempotent:
	// the same report id, segment and digest answer the same status; a
	// different digest for a stored segment is a conflict (RFC-026).
	PutResult(context.Context, *connect.Request[v3.PutResultRequest]) (*connect.Response[v3.PutResultResponse], error)
	// CommitResult closes a segmented report (RFC-026).
	CommitResult(context.Context, *connect.Request[v3.CommitResultRequest]) (*connect.Response[v3.CommitResultResponse], error)
	// GetResultStatus is the status of a report: what was received and what
	// is missing, so an interrupted upload resumes where it stopped.
	GetResultStatus(context.Context, *connect.Request[v3.GetResultStatusRequest]) (*connect.Response[v3.GetResultStatusResponse], error)
	// AbandonResult drops an uncommitted report.
	AbandonResult(context.Context, *connect.Request[v3.AbandonResultRequest]) (*connect.Response[v3.AbandonResultResponse], error)
	// PutManifest registers what the sensor is (RFC-033).
	PutManifest(context.Context, *connect.Request[v3.PutManifestRequest]) (*connect.Response[v3.PutManifestResponse], error)
	// GetManifest returns the current manifest digest and policy (RFC-033).
	GetManifest(context.Context, *connect.Request[v3.GetManifestRequest]) (*connect.Response[v3.GetManifestResponse], error)
	// PutConfigReport stores the sensor's preflight check results.
	PutConfigReport(context.Context, *connect.Request[v3.PutConfigReportRequest]) (*connect.Response[v3.PutConfigReportResponse], error)
	// GetSuppressions returns the active suppression rules (RFC-029 §4.5).
	GetSuppressions(context.Context, *connect.Request[v3.GetSuppressionsRequest]) (*connect.Response[v3.GetSuppressionsResponse], error)
	// CheckFingerprints tells which finding fingerprints the platform knows.
	CheckFingerprints(context.Context, *connect.Request[v3.CheckFingerprintsRequest]) (*connect.Response[v3.CheckFingerprintsResponse], error)
	// BaselineDiff splits fingerprints into new and pre-existing on a branch.
	BaselineDiff(context.Context, *connect.Request[v3.BaselineDiffRequest]) (*connect.Response[v3.BaselineDiffResponse], error)
	// IssueCertificate issues a client certificate for the sensor's registered
	// key, signed by the sensor CA. No CSR: the caller proved possession of the
	// key by signing the request (HTTPS binding) or by the TLS handshake (gRPC
	// binding). The sensor calls it again at two thirds of the lifetime.
	IssueCertificate(context.Context, *connect.Request[v3.IssueCertificateRequest]) (*connect.Response[v3.IssueCertificateResponse], error)
}

// NewSensorServiceClient constructs a client for the openctem.sensor.v3.SensorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSensorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SensorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sensorServiceMethods := v3.File_openctem_sensor_v3_sensor_proto.Services().ByName("SensorService").Methods()
	return &sensorServiceClient{
		hello: connect.NewClient[v3.HelloRequest, v3.HelloResponse](
			httpClient,
			baseURL+SensorServiceHelloProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("Hello")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[v3.HeartbeatRequest, v3.HeartbeatResponse](
			httpClient,
			baseURL+SensorServiceHeartbeatProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[v3.SubscribeRequest, v3.SubscribeResponse](
			httpClient,
			baseURL+SensorServiceSubscribeProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		claimCommands: connect.NewClient[v3.ClaimCommandsRequest, v3.ClaimCommandsResponse](
			httpClient,
			baseURL+SensorServiceClaimCommandsProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("ClaimCommands")),
			connect.WithClientOptions(opts...),
		),
		transitionCommand: connect.NewClient[v3.TransitionCommandRequest, v3.TransitionCommandResponse](
			httpClient,
			baseURL+SensorServiceTransitionCommandProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("TransitionCommand")),
			connect.WithClientOptions(opts...),
		),
		appendCommandLogs: connect.NewClient[v3.AppendCommandLogsRequest, v3.AppendCommandLogsResponse](
			httpClient,
			baseURL+SensorServiceAppendCommandLogsProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("AppendCommandLogs")),
			connect.WithClientOptions(opts...),
		),
		putResult: connect.NewClient[v3.PutResultRequest, v3.PutResultResponse](
			httpClient,
			baseURL+SensorServicePutResultProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("PutResult")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		commitResult: connect.NewClient[v3.CommitResultRequest, v3.CommitResultResponse](
			httpClient,
			baseURL+SensorServiceCommitResultProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("CommitResult")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		getResultStatus: connect.NewClient[v3.GetResultStatusRequest, v3.GetResultStatusResponse](
			httpClient,
			baseURL+SensorServiceGetResultStatusProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("GetResultStatus")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		abandonResult: connect.NewClient[v3.AbandonResultRequest, v3.AbandonResultResponse](
			httpClient,
			baseURL+SensorServiceAbandonResultProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("AbandonResult")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		putManifest: connect.NewClient[v3.PutManifestRequest, v3.PutManifestResponse](
			httpClient,
			baseURL+SensorServicePutManifestProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("PutManifest")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		getManifest: connect.NewClient[v3.GetManifestRequest, v3.GetManifestResponse](
			httpClient,
			baseURL+SensorServiceGetManifestProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("GetManifest")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		putConfigReport: connect.NewClient[v3.PutConfigReportRequest, v3.PutConfigReportResponse](
			httpClient,
			baseURL+SensorServicePutConfigReportProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("PutConfigReport")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		getSuppressions: connect.NewClient[v3.GetSuppressionsRequest, v3.GetSuppressionsResponse](
			httpClient,
			baseURL+SensorServiceGetSuppressionsProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("GetSuppressions")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		checkFingerprints: connect.NewClient[v3.CheckFingerprintsRequest, v3.CheckFingerprintsResponse](
			httpClient,
			baseURL+SensorServiceCheckFingerprintsProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("CheckFingerprints")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		baselineDiff: connect.NewClient[v3.BaselineDiffRequest, v3.BaselineDiffResponse](
			httpClient,
			baseURL+SensorServiceBaselineDiffProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("BaselineDiff")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		issueCertificate: connect.NewClient[v3.IssueCertificateRequest, v3.IssueCertificateResponse](
			httpClient,
			baseURL+SensorServiceIssueCertificateProcedure,
			connect.WithSchema(sensorServiceMethods.ByName("IssueCertificate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sensorServiceClient implements SensorServiceClient.
type sensorServiceClient struct {
	hello             *connect.Client[v3.HelloRequest, v3.HelloResponse]
	heartbeat         *connect.Client[v3.HeartbeatRequest, v3.HeartbeatResponse]
	subscribe         *connect.Client[v3.SubscribeRequest, v3.SubscribeResponse]
	claimCommands     *connect.Client[v3.ClaimCommandsRequest, v3.ClaimCommandsResponse]
	transitionCommand *connect.Client[v3.TransitionCommandRequest, v3.TransitionCommandResponse]
	appendCommandLogs *connect.Client[v3.AppendCommandLogsRequest, v3.AppendCommandLogsResponse]
	putResult         *connect.Client[v3.PutResultRequest, v3.PutResultResponse]
	commitResult      *connect.Client[v3.CommitResultRequest, v3.CommitResultResponse]
	getResultStatus   *connect.Client[v3.GetResultStatusRequest, v3.GetResultStatusResponse]
	abandonResult     *connect.Client[v3.AbandonResultRequest, v3.AbandonResultResponse]
	putManifest       *connect.Client[v3.PutManifestRequest, v3.PutManifestResponse]
	getManifest       *connect.Client[v3.GetManifestRequest, v3.GetManifestResponse]
	putConfigReport   *connect.Client[v3.PutConfigReportRequest, v3.PutConfigReportResponse]
	getSuppressions   *connect.Client[v3.GetSuppressionsRequest, v3.GetSuppressionsResponse]
	checkFingerprints *connect.Client[v3.CheckFingerprintsRequest, v3.CheckFingerprintsResponse]
	baselineDiff      *connect.Client[v3.BaselineDiffRequest, v3.BaselineDiffResponse]
	issueCertificate  *connect.Client[v3.IssueCertificateRequest, v3.IssueCertificateResponse]
}

// Hello calls openctem.sensor.v3.SensorService.Hello.
func (c *sensorServiceClient) Hello(ctx context.Context, req *connect.Request[v3.HelloRequest]) (*connect.Response[v3.HelloResponse], error) {
	return c.hello.CallUnary(ctx, req)
}

// Heartbeat calls openctem.sensor.v3.SensorService.Heartbeat.
func (c *sensorServiceClient) Heartbeat(ctx context.Context, req *connect.Request[v3.HeartbeatRequest]) (*connect.Response[v3.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// Subscribe calls openctem.sensor.v3.SensorService.Subscribe.
func (c *sensorServiceClient) Subscribe(ctx context.Context, req *connect.Request[v3.SubscribeRequest]) (*connect.ServerStreamForClient[v3.SubscribeResponse], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// ClaimCommands calls openctem.sensor.v3.SensorService.ClaimCommands.
func (c *sensorServiceClient) ClaimCommands(ctx context.Context, req *connect.Request[v3.ClaimCommandsRequest]) (*connect.Response[v3.ClaimCommandsResponse], error) {
	return c.claimCommands.CallUnary(ctx, req)
}

// TransitionCommand calls openctem.sensor.v3.SensorService.TransitionCommand.
func (c *sensorServiceClient) TransitionCommand(ctx context.Context, req *connect.Request[v3.TransitionCommandRequest]) (*connect.Response[v3.TransitionCommandResponse], error) {
	return c.transitionCommand.CallUnary(ctx, req)
}

// AppendCommandLogs calls openctem.sensor.v3.SensorService.AppendCommandLogs.
func (c *sensorServiceClient) AppendCommandLogs(ctx context.Context, req *connect.Request[v3.AppendCommandLogsRequest]) (*connect.Response[v3.AppendCommandLogsResponse], error) {
	return c.appendCommandLogs.CallUnary(ctx, req)
}

// PutResult calls openctem.sensor.v3.SensorService.PutResult.
func (c *sensorServiceClient) PutResult(ctx context.Context, req *connect.Request[v3.PutResultRequest]) (*connect.Response[v3.PutResultResponse], error) {
	return c.putResult.CallUnary(ctx, req)
}

// CommitResult calls openctem.sensor.v3.SensorService.CommitResult.
func (c *sensorServiceClient) CommitResult(ctx context.Context, req *connect.Request[v3.CommitResultRequest]) (*connect.Response[v3.CommitResultResponse], error) {
	return c.commitResult.CallUnary(ctx, req)
}

// GetResultStatus calls openctem.sensor.v3.SensorService.GetResultStatus.
func (c *sensorServiceClient) GetResultStatus(ctx context.Context, req *connect.Request[v3.GetResultStatusRequest]) (*connect.Response[v3.GetResultStatusResponse], error) {
	return c.getResultStatus.CallUnary(ctx, req)
}

// AbandonResult calls openctem.sensor.v3.SensorService.AbandonResult.
func (c *sensorServiceClient) AbandonResult(ctx context.Context, req *connect.Request[v3.AbandonResultRequest]) (*connect.Response[v3.AbandonResultResponse], error) {
	return c.abandonResult.CallUnary(ctx, req)
}

// PutManifest calls openctem.sensor.v3.SensorService.PutManifest.
func (c *sensorServiceClient) PutManifest(ctx context.Context, req *connect.Request[v3.PutManifestRequest]) (*connect.Response[v3.PutManifestResponse], error) {
	return c.putManifest.CallUnary(ctx, req)
}

// GetManifest calls openctem.sensor.v3.SensorService.GetManifest.
func (c *sensorServiceClient) GetManifest(ctx context.Context, req *connect.Request[v3.GetManifestRequest]) (*connect.Response[v3.GetManifestResponse], error) {
	return c.getManifest.CallUnary(ctx, req)
}

// PutConfigReport calls openctem.sensor.v3.SensorService.PutConfigReport.
func (c *sensorServiceClient) PutConfigReport(ctx context.Context, req *connect.Request[v3.PutConfigReportRequest]) (*connect.Response[v3.PutConfigReportResponse], error) {
	return c.putConfigReport.CallUnary(ctx, req)
}

// GetSuppressions calls openctem.sensor.v3.SensorService.GetSuppressions.
func (c *sensorServiceClient) GetSuppressions(ctx context.Context, req *connect.Request[v3.GetSuppressionsRequest]) (*connect.Response[v3.GetSuppressionsResponse], error) {
	return c.getSuppressions.CallUnary(ctx, req)
}

// CheckFingerprints calls openctem.sensor.v3.SensorService.CheckFingerprints.
func (c *sensorServiceClient) CheckFingerprints(ctx context.Context, req *connect.Request[v3.CheckFingerprintsRequest]) (*connect.Response[v3.CheckFingerprintsResponse], error) {
	return c.checkFingerprints.CallUnary(ctx, req)
}

// BaselineDiff calls openctem.sensor.v3.SensorService.BaselineDiff.
func (c *sensorServiceClient) BaselineDiff(ctx context.Context, req *connect.Request[v3.BaselineDiffRequest]) (*connect.Response[v3.BaselineDiffResponse], error) {
	return c.baselineDiff.CallUnary(ctx, req)
}

// IssueCertificate calls openctem.sensor.v3.SensorService.IssueCertificate.
func (c *sensorServiceClient) IssueCertificate(ctx context.Context, req *connect.Request[v3.IssueCertificateRequest]) (*connect.Response[v3.IssueCertificateResponse], error) {
	return c.issueCertificate.CallUnary(ctx, req)
}

// SensorServiceHandler is an implementation of the openctem.sensor.v3.SensorService service.
type SensorServiceHandler interface {
	// Hello returns the protocol level, the features and limits this platform
	// serves and where its v3 endpoints are.
	Hello(context.Context, *connect.Request[v3.HelloRequest]) (*connect.Response[v3.HelloResponse], error)
	// Heartbeat records the sensor's state and answers with the doorbell
	// (RFC-029 §4.3, RFC-035).
	Heartbeat(context.Context, *connect.Request[v3.HeartbeatRequest]) (*connect.Response[v3.HeartbeatResponse], error)
	// Subscribe is the control stream: the platform pushes the doorbell (work
	// waiting, cancels, pause, drain, key rotation, manifest requests) as soon as
	// it changes, plus a keepalive. It never carries a job: jobs are claimed with
	// ClaimCommands, so the database lease stays the only source of truth and a
	// lost stream loses nothing.
	Subscribe(context.Context, *connect.Request[v3.SubscribeRequest], *connect.ServerStream[v3.SubscribeResponse]) error
	// ClaimCommands claims up to limit commands this sensor may run now.
	ClaimCommands(context.Context, *connect.Request[v3.ClaimCommandsRequest]) (*connect.Response[v3.ClaimCommandsResponse], error)
	// TransitionCommand moves a command this sensor holds: claim, start,
	// complete, fail or release (RFC-029, RFC-030 §5.12).
	TransitionCommand(context.Context, *connect.Request[v3.TransitionCommandRequest]) (*connect.Response[v3.TransitionCommandResponse], error)
	// AppendCommandLogs appends a batch of task log lines (RFC-029 §4.4.1).
	AppendCommandLogs(context.Context, *connect.Request[v3.AppendCommandLogsRequest]) (*connect.Response[v3.AppendCommandLogsResponse], error)
	// PutResult uploads a whole CTIS report, or one segment of it. Idempotent:
	// the same report id, segment and digest answer the same status; a
	// different digest for a stored segment is a conflict (RFC-026).
	PutResult(context.Context, *connect.Request[v3.PutResultRequest]) (*connect.Response[v3.PutResultResponse], error)
	// CommitResult closes a segmented report (RFC-026).
	CommitResult(context.Context, *connect.Request[v3.CommitResultRequest]) (*connect.Response[v3.CommitResultResponse], error)
	// GetResultStatus is the status of a report: what was received and what
	// is missing, so an interrupted upload resumes where it stopped.
	GetResultStatus(context.Context, *connect.Request[v3.GetResultStatusRequest]) (*connect.Response[v3.GetResultStatusResponse], error)
	// AbandonResult drops an uncommitted report.
	AbandonResult(context.Context, *connect.Request[v3.AbandonResultRequest]) (*connect.Response[v3.AbandonResultResponse], error)
	// PutManifest registers what the sensor is (RFC-033).
	PutManifest(context.Context, *connect.Request[v3.PutManifestRequest]) (*connect.Response[v3.PutManifestResponse], error)
	// GetManifest returns the current manifest digest and policy (RFC-033).
	GetManifest(context.Context, *connect.Request[v3.GetManifestRequest]) (*connect.Response[v3.GetManifestResponse], error)
	// PutConfigReport stores the sensor's preflight check results.
	PutConfigReport(context.Context, *connect.Request[v3.PutConfigReportRequest]) (*connect.Response[v3.PutConfigReportResponse], error)
	// GetSuppressions returns the active suppression rules (RFC-029 §4.5).
	GetSuppressions(context.Context, *connect.Request[v3.GetSuppressionsRequest]) (*connect.Response[v3.GetSuppressionsResponse], error)
	// CheckFingerprints tells which finding fingerprints the platform knows.
	CheckFingerprints(context.Context, *connect.Request[v3.CheckFingerprintsRequest]) (*connect.Response[v3.CheckFingerprintsResponse], error)
	// BaselineDiff splits fingerprints into new and pre-existing on a branch.
	BaselineDiff(context.Context, *connect.Request[v3.BaselineDiffRequest]) (*connect.Response[v3.BaselineDiffResponse], error)
	// IssueCertificate issues a client certificate for the sensor's registered
	// key, signed by the sensor CA. No CSR: the caller proved possession of the
	// key by signing the request (HTTPS binding) or by the TLS handshake (gRPC
	// binding). The sensor calls it again at two thirds of the lifetime.
	IssueCertificate(context.Context, *connect.Request[v3.IssueCertificateRequest]) (*connect.Response[v3.IssueCertificateResponse], error)
}

// NewSensorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSensorServiceHandler(svc SensorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sensorServiceMethods := v3.File_openctem_sensor_v3_sensor_proto.Services().ByName("SensorService").Methods()
	sensorServiceHelloHandler := connect.NewUnaryHandler(
		SensorServiceHelloProcedure,
		svc.Hello,
		connect.WithSchema(sensorServiceMethods.ByName("Hello")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceHeartbeatHandler := connect.NewUnaryHandler(
		SensorServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(sensorServiceMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceSubscribeHandler := connect.NewServerStreamHandler(
		SensorServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(sensorServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceClaimCommandsHandler := connect.NewUnaryHandler(
		SensorServiceClaimCommandsProcedure,
		svc.ClaimCommands,
		connect.WithSchema(sensorServiceMethods.ByName("ClaimCommands")),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceTransitionCommandHandler := connect.NewUnaryHandler(
		SensorServiceTransitionCommandProcedure,
		svc.TransitionCommand,
		connect.WithSchema(sensorServiceMethods.ByName("TransitionCommand")),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceAppendCommandLogsHandler := connect.NewUnaryHandler(
		SensorServiceAppendCommandLogsProcedure,
		svc.AppendCommandLogs,
		connect.WithSchema(sensorServiceMethods.ByName("AppendCommandLogs")),
		connect.WithHandlerOptions(opts...),
	)
	sensorServicePutResultHandler := connect.NewUnaryHandler(
		SensorServicePutResultProcedure,
		svc.PutResult,
		connect.WithSchema(sensorServiceMethods.ByName("PutResult")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceCommitResultHandler := connect.NewUnaryHandler(
		SensorServiceCommitResultProcedure,
		svc.CommitResult,
		connect.WithSchema(sensorServiceMethods.ByName("CommitResult")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceGetResultStatusHandler := connect.NewUnaryHandler(
		SensorServiceGetResultStatusProcedure,
		svc.GetResultStatus,
		connect.WithSchema(sensorServiceMethods.ByName("GetResultStatus")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceAbandonResultHandler := connect.NewUnaryHandler(
		SensorServiceAbandonResultProcedure,
		svc.AbandonResult,
		connect.WithSchema(sensorServiceMethods.ByName("AbandonResult")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	sensorServicePutManifestHandler := connect.NewUnaryHandler(
		SensorServicePutManifestProcedure,
		svc.PutManifest,
		connect.WithSchema(sensorServiceMethods.ByName("PutManifest")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceGetManifestHandler := connect.NewUnaryHandler(
		SensorServiceGetManifestProcedure,
		svc.GetManifest,
		connect.WithSchema(sensorServiceMethods.ByName("GetManifest")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	sensorServicePutConfigReportHandler := connect.NewUnaryHandler(
		SensorServicePutConfigReportProcedure,
		svc.PutConfigReport,
		connect.WithSchema(sensorServiceMethods.ByName("PutConfigReport")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceGetSuppressionsHandler := connect.NewUnaryHandler(
		SensorServiceGetSuppressionsProcedure,
		svc.GetSuppressions,
		connect.WithSchema(sensorServiceMethods.ByName("GetSuppressions")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceCheckFingerprintsHandler := connect.NewUnaryHandler(
		SensorServiceCheckFingerprintsProcedure,
		svc.CheckFingerprints,
		connect.WithSchema(sensorServiceMethods.ByName("CheckFingerprints")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceBaselineDiffHandler := connect.NewUnaryHandler(
		SensorServiceBaselineDiffProcedure,
		svc.BaselineDiff,
		connect.WithSchema(sensorServiceMethods.ByName("BaselineDiff")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	sensorServiceIssueCertificateHandler := connect.NewUnaryHandler(
		SensorServiceIssueCertificateProcedure,
		svc.IssueCertificate,
		connect.WithSchema(sensorServiceMethods.ByName("IssueCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openctem.sensor.v3.SensorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SensorServiceHelloProcedure:
			sensorServiceHelloHandler.ServeHTTP(w, r)
		case SensorServiceHeartbeatProcedure:
			sensorServiceHeartbeatHandler.ServeHTTP(w, r)
		case SensorServiceSubscribeProcedure:
			sensorServiceSubscribeHandler.ServeHTTP(w, r)
		case SensorServiceClaimCommandsProcedure:
			sensorServiceClaimCommandsHandler.ServeHTTP(w, r)
		case SensorServiceTransitionCommandProcedure:
			sensorServiceTransitionCommandHandler.ServeHTTP(w, r)
		case SensorServiceAppendCommandLogsProcedure:
			sensorServiceAppendCommandLogsHandler.ServeHTTP(w, r)
		case SensorServicePutResultProcedure:
			sensorServicePutResultHandler.ServeHTTP(w, r)
		case SensorServiceCommitResultProcedure:
			sensorServiceCommitResultHandler.ServeHTTP(w, r)
		case SensorServiceGetResultStatusProcedure:
			sensorServiceGetResultStatusHandler.ServeHTTP(w, r)
		case SensorServiceAbandonResultProcedure:
			sensorServiceAbandonResultHandler.ServeHTTP(w, r)
		case SensorServicePutManifestProcedure:
			sensorServicePutManifestHandler.ServeHTTP(w, r)
		case SensorServiceGetManifestProcedure:
			sensorServiceGetManifestHandler.ServeHTTP(w, r)
		case SensorServicePutConfigReportProcedure:
			sensorServicePutConfigReportHandler.ServeHTTP(w, r)
		case SensorServiceGetSuppressionsProcedure:
			sensorServiceGetSuppressionsHandler.ServeHTTP(w, r)
		case SensorServiceCheckFingerprintsProcedure:
			sensorServiceCheckFingerprintsHandler.ServeHTTP(w, r)
		case SensorServiceBaselineDiffProcedure:
			sensorServiceBaselineDiffHandler.ServeHTTP(w, r)
		case SensorServiceIssueCertificateProcedure:
			sensorServiceIssueCertificateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSensorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSensorServiceHandler struct{}

func (UnimplementedSensorServiceHandler) Hello(context.Context, *connect.Request[v3.HelloRequest]) (*connect.Response[v3.HelloResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.Hello is not implemented"))
}

func (UnimplementedSensorServiceHandler) Heartbeat(context.Context, *connect.Request[v3.HeartbeatRequest]) (*connect.Response[v3.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.Heartbeat is not implemented"))
}

func (UnimplementedSensorServiceHandler) Subscribe(context.Context, *connect.Request[v3.SubscribeRequest], *connect.ServerStream[v3.SubscribeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.Subscribe is not implemented"))
}

func (UnimplementedSensorServiceHandler) ClaimCommands(context.Context, *connect.Request[v3.ClaimCommandsRequest]) (*connect.Response[v3.ClaimCommandsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.ClaimCommands is not implemented"))
}

func (UnimplementedSensorServiceHandler) TransitionCommand(context.Context, *connect.Request[v3.TransitionCommandRequest]) (*connect.Response[v3.TransitionCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.TransitionCommand is not implemented"))
}

func (UnimplementedSensorServiceHandler) AppendCommandLogs(context.Context, *connect.Request[v3.AppendCommandLogsRequest]) (*connect.Response[v3.AppendCommandLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.AppendCommandLogs is not implemented"))
}

func (UnimplementedSensorServiceHandler) PutResult(context.Context, *connect.Request[v3.PutResultRequest]) (*connect.Response[v3.PutResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.PutResult is not implemented"))
}

func (UnimplementedSensorServiceHandler) CommitResult(context.Context, *connect.Request[v3.CommitResultRequest]) (*connect.Response[v3.CommitResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.CommitResult is not implemented"))
}

func (UnimplementedSensorServiceHandler) GetResultStatus(context.Context, *connect.Request[v3.GetResultStatusRequest]) (*connect.Response[v3.GetResultStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.GetResultStatus is not implemented"))
}

func (UnimplementedSensorServiceHandler) AbandonResult(context.Context, *connect.Request[v3.AbandonResultRequest]) (*connect.Response[v3.AbandonResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.AbandonResult is not implemented"))
}

func (UnimplementedSensorServiceHandler) PutManifest(context.Context, *connect.Request[v3.PutManifestRequest]) (*connect.Response[v3.PutManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.PutManifest is not implemented"))
}

func (UnimplementedSensorServiceHandler) GetManifest(context.Context, *connect.Request[v3.GetManifestRequest]) (*connect.Response[v3.GetManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.GetManifest is not implemented"))
}

func (UnimplementedSensorServiceHandler) PutConfigReport(context.Context, *connect.Request[v3.PutConfigReportRequest]) (*connect.Response[v3.PutConfigReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.PutConfigReport is not implemented"))
}

func (UnimplementedSensorServiceHandler) GetSuppressions(context.Context, *connect.Request[v3.GetSuppressionsRequest]) (*connect.Response[v3.GetSuppressionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.GetSuppressions is not implemented"))
}

func (UnimplementedSensorServiceHandler) CheckFingerprints(context.Context, *connect.Request[v3.CheckFingerprintsRequest]) (*connect.Response[v3.CheckFingerprintsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.CheckFingerprints is not implemented"))
}

func (UnimplementedSensorServiceHandler) BaselineDiff(context.Context, *connect.Request[v3.BaselineDiffRequest]) (*connect.Response[v3.BaselineDiffResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.BaselineDiff is not implemented"))
}

func (UnimplementedSensorServiceHandler) IssueCertificate(context.Context, *connect.Request[v3.IssueCertificateRequest]) (*connect.Response[v3.IssueCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openctem.sensor.v3.SensorService.IssueCertificate is not implemented"))
}
