// Command genalias writes pkg/ctis/zz_generated_aliases.go: one type alias,
// constant, variable or wrapper function in package ctis for every exported
// identifier of the root package of github.com/openctemio/ctis, at the
// version go.mod requires. pkg/ctis therefore cannot drift from the CTIS
// module: it has no copy of the types or converters, only names for them.
//
// Identifiers pkg/ctis defines itself (sdk-only behavior around the same
// types), or leaves out on purpose, are listed in skip.
//
// Usage (from the sdk-go root): go generate ./pkg/ctis
// CI (scripts/check-ctis-parity.sh) regenerates the file and fails on a diff.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const module = "github.com/openctemio/ctis"

// skip names upstream identifiers that pkg/ctis implements itself (the
// value is the file) or leaves out (the value says why).
var skip = map[string]string{
	// SARIF is converted by core.SARIFParser through the module's importer
	// package (input limits, asset rule); the bare converter is not
	// re-exported, so the SDK has one SARIF path.
	"FromSARIF": "left out: use core.SARIFParser",
	// SARIFLog and SARIFRun add versionControlProvenance (and
	// SARIFRun.Repository) to the module's SARIF model; the nested SARIF
	// types are the module's.
	"SARIFLog": "sarif.go",
	"SARIFRun": "sarif.go",
}

func main() {
	out := "zz_generated_aliases.go"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}
	dir, version := moduleDir()
	src, err := generate(dir, version)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(out, src, 0o600); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "genalias:", err)
	os.Exit(1)
}

func moduleDir() (dir, version string) {
	cmd := exec.Command("go", "list", "-m", "-json", module)
	cmd.Stderr = os.Stderr
	b, err := cmd.Output()
	if err != nil {
		fail(fmt.Errorf("go list -m %s: %w", module, err))
	}
	var m struct{ Dir, Version string }
	if err := json.Unmarshal(b, &m); err != nil {
		fail(err)
	}
	if m.Dir == "" {
		fail(fmt.Errorf("%s is not downloaded (run go mod download)", module))
	}
	return m.Dir, m.Version
}

type decls struct {
	types, consts, vars []string
	funcs               []*ast.FuncDecl
}

func generate(dir, version string) ([]byte, error) {
	fset := token.NewFileSet()
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	var d decls
	for _, f := range files {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		af, err := parser.ParseFile(fset, f, nil, 0)
		if err != nil {
			return nil, err
		}
		if af.Name.Name != "ctis" {
			continue
		}
		collect(af, &d)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by genalias from %s %s; DO NOT EDIT.\n\n", module, version)
	b.WriteString("package ctis\n\nimport upstream \"" + module + "\"\n\n")
	b.WriteString("// Types: every exported type of " + module + ".\ntype (\n")
	for _, n := range d.types {
		fmt.Fprintf(&b, "\t%s = upstream.%s\n", n, n)
	}
	b.WriteString(")\n\n// Constants.\nconst (\n")
	for _, n := range d.consts {
		fmt.Fprintf(&b, "\t%s = upstream.%s\n", n, n)
	}
	b.WriteString(")\n")
	if len(d.vars) > 0 {
		b.WriteString("\n// Variables.\nvar (\n")
		for _, n := range d.vars {
			fmt.Fprintf(&b, "\t%s = upstream.%s\n", n, n)
		}
		b.WriteString(")\n")
	}
	for _, fn := range d.funcs {
		if err := writeFunc(&b, fset, fn); err != nil {
			return nil, err
		}
	}
	return format.Source(b.Bytes())
}

func collect(af *ast.File, d *decls) {
	for _, decl := range af.Decls {
		switch decl := decl.(type) {
		case *ast.FuncDecl:
			if decl.Recv != nil || !decl.Name.IsExported() || skip[decl.Name.Name] != "" {
				continue
			}
			if decl.Type.TypeParams != nil {
				fail(fmt.Errorf("generic function %s: extend genalias", decl.Name.Name))
			}
			d.funcs = append(d.funcs, decl)
		case *ast.GenDecl:
			for _, spec := range decl.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					if s.Name.IsExported() && skip[s.Name.Name] == "" {
						if s.TypeParams != nil {
							fail(fmt.Errorf("generic type %s: extend genalias", s.Name.Name))
						}
						d.types = append(d.types, s.Name.Name)
					}
				case *ast.ValueSpec:
					for _, n := range s.Names {
						if !n.IsExported() || skip[n.Name] != "" {
							continue
						}
						if decl.Tok == token.CONST {
							d.consts = append(d.consts, n.Name)
						} else {
							d.vars = append(d.vars, n.Name)
						}
					}
				}
			}
		}
	}
}

// writeFunc writes a wrapper with the upstream signature. Parameter and
// result types are printed unqualified: inside pkg/ctis they name the
// aliases above, which are the upstream types.
func writeFunc(b *bytes.Buffer, fset *token.FileSet, fn *ast.FuncDecl) error {
	var args []string
	params := &ast.FieldList{}
	for i, f := range fn.Type.Params.List {
		names := f.Names
		if len(names) == 0 {
			names = []*ast.Ident{ast.NewIdent(fmt.Sprintf("p%d", i))}
		}
		var renamed []*ast.Ident
		for j, n := range names {
			name := n.Name
			if name == "_" {
				name = fmt.Sprintf("p%d_%d", i, j)
			}
			renamed = append(renamed, ast.NewIdent(name))
			if _, ok := f.Type.(*ast.Ellipsis); ok {
				name += "..."
			}
			args = append(args, name)
		}
		params.List = append(params.List, &ast.Field{Names: renamed, Type: f.Type})
	}
	sig := &ast.FuncType{Params: params, Results: fn.Type.Results}
	var s bytes.Buffer
	if err := printer.Fprint(&s, fset, sig); err != nil {
		return err
	}
	call := fmt.Sprintf("upstream.%s(%s)", fn.Name.Name, strings.Join(args, ", "))
	body := "return " + call
	if fn.Type.Results == nil || len(fn.Type.Results.List) == 0 {
		body = call
	}
	fmt.Fprintf(b, "\n// %s calls %s.%s.\nfunc %s%s {\n\t%s\n}\n",
		fn.Name.Name, module, fn.Name.Name, fn.Name.Name, strings.TrimPrefix(s.String(), "func"), body)
	return nil
}
